# Generated by Django 3.1.7 on 2023-06-05 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sehler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sehler')),
                ('tel', models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefon belgisi')),
                ('reg_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='reg nomer')),
                ('ind_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='indeks nomer')),
                ('kpp_num', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Salgysy')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Gysga beyany')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
            ],
            options={
                'verbose_name': 'Seh',
                'verbose_name_plural': 'Sehler',
            },
        ),
        migrations.CreateModel(
            name='Wez_other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='wezipesi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Gysga beyany')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Other wezipesi',
                'verbose_name_plural': 'Other Wezipeler',
            },
        ),
        migrations.CreateModel(
            name='Other_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faa', models.CharField(blank=True, max_length=100, null=True, verbose_name='F.A.A')),
                ('birth_date', models.DateField(default=django.utils.timezone.now, verbose_name='Doglan senesi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Öý salgysy')),
                ('user_code', models.CharField(blank=True, default=users.models.random_string, max_length=12, null=True, unique=True)),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.office')),
                ('seh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler')),
                ('wez', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.wez_other')),
            ],
            options={
                'verbose_name': 'Başga işgär',
                'verbose_name_plural': 'Başga işgärler',
            },
        ),
    ]
