# Generated by Django 3.1.7 on 2023-06-07 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_other_users_sehler_wez_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_users',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.office'),
        ),
        migrations.AlterField(
            model_name='other_users',
            name='seh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler'),
        ),
        migrations.AlterField(
            model_name='other_users',
            name='wez',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.wez_other'),
        ),
    ]
