# Generated by Django 4.2.1 on 2023-07-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230607_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='sehler',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.office'),
        ),
    ]
