# Generated by Django 4.2.1 on 2023-07-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_sehler_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sehler',
            name='office',
        ),
        migrations.AddField(
            model_name='office',
            name='all_sehler',
            field=models.ManyToManyField(blank=True, null=True, to='users.sehler'),
        ),
    ]
