# Generated by Django 4.2.1 on 2023-07-02 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_sehler_office_office_all_sehler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='all_sehler',
        ),
        migrations.AddField(
            model_name='sehler',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_sehs', to='users.office'),
        ),
    ]
