# Generated by Django 4.2.2 on 2023-07-13 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_office_all_sehler_sehler_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusers',
            name='sehs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sehs', to='users.sehler'),
        ),
    ]
