# Generated by Django 4.2.1 on 2023-07-21 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_cigmal_zawodlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faa', models.CharField(blank=True, max_length=100, null=True, verbose_name='F.A.A')),
                ('birth_date', models.DateField(default=django.utils.timezone.now, verbose_name='Doglan senesi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Öý salgysy')),
                ('user_code', models.CharField(blank=True, default=users.models.random_string, max_length=12, null=True, unique=True)),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('seh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler')),
                ('wez', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.wez_other')),
            ],
            options={
                'verbose_name': 'Daşary ýurt klient',
                'verbose_name_plural': 'Daşary ýurt klientler',
            },
        ),
    ]
