# Generated by Django 4.2.1 on 2023-07-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_manager_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sehler',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sehler',
            name='ind_num',
        ),
        migrations.RemoveField(
            model_name='sehler',
            name='kpp_num',
        ),
        migrations.RemoveField(
            model_name='sehler',
            name='reg_num',
        ),
        migrations.AlterField(
            model_name='sehler',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sehler'),
        ),
    ]
