# Generated by Django 4.2.1 on 2023-07-23 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_sehler_description_remove_sehler_ind_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primary_Seh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sehiň ady')),
            ],
            options={
                'verbose_name': 'Seh',
                'verbose_name_plural': 'Sehler',
            },
        ),
        migrations.AlterModelOptions(
            name='sehler',
            options={'verbose_name': 'sub Seh', 'verbose_name_plural': 'sub Sehler'},
        ),
        migrations.AddField(
            model_name='sehler',
            name='pr_seh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.primary_seh'),
        ),
    ]
