# Generated by Django 3.1.7 on 2023-04-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolek_hasaplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sene', models.DateField(blank=True, default='', null=True, verbose_name='Senesi')),
                ('ostatok', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Her günüň ostatogy')),
                ('girdeji', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Her günüň girdejisi')),
                ('cykdajy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Her günüň çykdajysy')),
                ('sebap', models.CharField(blank=True, max_length=100, verbose_name='girdejinin ya-da cykdajynyn sebabi')),
                ('bellik', models.TextField(blank=True, verbose_name='Bellik')),
            ],
            options={
                'verbose_name': 'Bölek hasap',
                'verbose_name_plural': 'Bölek hasaplar',
            },
        ),
        migrations.CreateModel(
            name='Gir_ostatok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sene', models.DateField(blank=True, default='', null=True, verbose_name='Senesi')),
                ('ostatok', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Her günüň ostatogy')),
            ],
            options={
                'verbose_name': 'Ostatok',
                'verbose_name_plural': 'Ostatoklar',
            },
        ),
        migrations.CreateModel(
            name='Ojidanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_sent_id', models.IntegerField(blank=True, default=None, null=True)),
                ('u_came_id', models.IntegerField(blank=True, default=None, null=True)),
                ('sene', models.DateField(blank=True, default='', null=True, verbose_name='Senesi')),
                ('cash', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Nagt pul')),
                ('sebap', models.CharField(blank=True, max_length=100, verbose_name='Geçirim puluň sebäbi')),
                ('bellik', models.TextField(blank=True, verbose_name='Bellik')),
                ('tassyk', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Ojidanie',
                'verbose_name_plural': 'Ojidaniyalar',
            },
        ),
    ]
