# Generated by Django 3.1.7 on 2023-04-19 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gir_ostatok',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ostatok', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bolek_hasaplar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_hasap', to=settings.AUTH_USER_MODEL),
        ),
    ]
