# Generated by Django 3.1.7 on 2023-04-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0002_auto_20230419_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolek_hasaplar',
            name='cykdajy_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Her günüň çykdajysy'),
        ),
        migrations.AddField(
            model_name='bolek_hasaplar',
            name='girdeji_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Her günüň girdejisi'),
        ),
    ]
