# Generated by Django 3.1.7 on 2023-04-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0003_auto_20230428_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='cykdajy_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Her günüň çykdajysy dollarda'),
        ),
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='girdeji_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Her günüň girdejisi dollarda'),
        ),
    ]
