# Generated by Django 3.1.7 on 2023-04-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0004_auto_20230428_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='cykdajy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Her günüň çykdajysy'),
        ),
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='cykdajy_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Her günüň çykdajysy dollarda'),
        ),
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='girdeji',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Her günüň girdejisi'),
        ),
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='girdeji_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Her günüň girdejisi dollarda'),
        ),
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='ostatok',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Her günüň ostatogy'),
        ),
        migrations.AlterField(
            model_name='gir_ostatok',
            name='ostatok',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Her günüň ostatogy'),
        ),
        migrations.AlterField(
            model_name='ojidanie',
            name='cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Nagt pul'),
        ),
    ]
