# Generated by Django 3.1.7 on 2023-05-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0006_auto_20230429_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojidanie',
            name='u_came_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
