# Generated by Django 3.1.7 on 2023-05-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0008_auto_20230511_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojidanie',
            name='u_came_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
