# Generated by Django 3.1.7 on 2023-05-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0009_auto_20230513_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojidanie',
            name='bellik',
            field=models.TextField(blank=True, null=True, verbose_name='Bellik'),
        ),
    ]
