# Generated by Django 3.1.7 on 2023-05-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0010_auto_20230513_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojidanie',
            name='bellik',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Bellik'),
        ),
    ]
