# Generated by Django 3.1.7 on 2023-05-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0011_auto_20230513_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojidanie',
            name='bellik',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Bellik'),
        ),
        migrations.AlterField(
            model_name='ojidanie',
            name='sebap',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Geçirim puluň sebäbi'),
        ),
    ]
