# Generated by Django 3.1.7 on 2023-05-13 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0013_auto_20230513_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojidanie',
            name='sene',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 13, 9, 33, 42, 760674), null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='ojidanie',
            name='u_came_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
