# Generated by Django 3.1.7 on 2023-05-17 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0014_auto_20230513_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolek_hasaplar',
            name='kurs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='$ kursy'),
        ),
        migrations.AlterField(
            model_name='ojidanie',
            name='sene',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 17, 16, 42, 4, 752779), null=True, verbose_name='Senesi'),
        ),
    ]
