# Generated by Django 3.1.7 on 2023-05-17 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0015_auto_20230517_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='sene',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 17, 17, 11, 8, 637145), null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='ojidanie',
            name='sene',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 17, 17, 11, 8, 637145), null=True, verbose_name='Senesi'),
        ),
    ]
