# Generated by Django 3.1.7 on 2023-05-20 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0016_auto_20230517_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gelen_sklat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harydyn_ady', models.CharField(blank=True, max_length=500, null=True, verbose_name='Harydyň ady')),
                ('nirden_gelen', models.CharField(blank=True, max_length=1000, null=True, verbose_name='haryt nirden geldi')),
                ('modeli', models.CharField(blank=True, max_length=500, null=True, verbose_name='Harydyň modeli')),
                ('sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Harydyň sany')),
                ('olceg_birligi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Harydyň ölçeg birligi')),
                ('oz_bahasy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Özüne düşýän bahasy')),
                ('sene', models.DateField(blank=True, default=datetime.datetime(2023, 5, 20, 10, 13, 49, 917549), null=True, verbose_name='Senesi')),
                ('bellik', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Bellik')),
            ],
            options={
                'verbose_name': 'Gelen haryt',
                'verbose_name_plural': 'Gelen harytlar',
            },
        ),
        migrations.CreateModel(
            name='Giden_sklat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harydyn_ady', models.CharField(blank=True, max_length=500, null=True, verbose_name='Harydyň ady')),
                ('nirden_gelen', models.CharField(blank=True, max_length=1000, null=True, verbose_name='haryt nirden geldi')),
                ('modeli', models.CharField(blank=True, max_length=500, null=True, verbose_name='Harydyň modeli')),
                ('sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Harydyň sany')),
                ('olceg_birligi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Harydyň ölçeg birligi')),
                ('oz_bahasy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Özüne düşýän bahasy')),
                ('sene', models.DateField(blank=True, default=datetime.datetime(2023, 5, 20, 10, 13, 49, 917549), null=True, verbose_name='Senesi')),
                ('bellik', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Bellik')),
            ],
            options={
                'verbose_name': 'Giden haryt',
                'verbose_name_plural': 'Giden harytlar',
            },
        ),
        migrations.CreateModel(
            name='Inwentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harydyn_ady', models.CharField(blank=True, max_length=500, null=True, verbose_name='Harydyň ady')),
                ('bahasy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bahasy')),
                ('nirde_dur', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Haryt nirde dur')),
                ('bellik', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=datetime.datetime(2023, 5, 20, 10, 13, 49, 917549), null=True, verbose_name='Senesi')),
            ],
            options={
                'verbose_name': 'Inwentar',
                'verbose_name_plural': 'Inwentarlar',
            },
        ),
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='sene',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 20, 10, 13, 49, 917549), null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='ojidanie',
            name='sene',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 20, 10, 13, 49, 917549), null=True, verbose_name='Senesi'),
        ),
    ]
