# Generated by Django 3.1.7 on 2023-05-22 06:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shu', '0017_auto_20230520_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='sene',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 22, 11, 21, 38, 425986), null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='gelen_sklat',
            name='sene',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 22, 11, 21, 38, 427646), null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='giden_sklat',
            name='sene',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 22, 11, 21, 38, 427646), null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='inwentar',
            name='sene',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 22, 11, 21, 38, 427646), null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='ojidanie',
            name='sene',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 22, 11, 21, 38, 426649), null=True, verbose_name='Senesi'),
        ),
        migrations.CreateModel(
            name='Gundelik_halta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sene', models.DateField(blank=True, default=datetime.datetime(2023, 5, 22, 11, 21, 38, 427646), null=True, verbose_name='Senesi')),
                ('h_olceg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Haltan olcegi')),
                ('h_gornusi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Harydyň ady')),
                ('abathalta_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Abat haltan sany')),
                ('abathalta_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Abat haltan kg')),
                ('brakhalta_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Brak haltan sany')),
                ('brakhalta_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Brak haltan kg')),
                ('sarp_sapak', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Dikilyan halta gityan sapak')),
                ('othod_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Brak haltan kg')),
                ('katyska_agram', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Katuskan agramy kg')),
                ('nirden_gelen', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nirden gelen rulon')),
                ('enjam', models.CharField(blank=True, max_length=500, null=True, verbose_name='Haysy enjamda dikilen')),
                ('bellik', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Bellik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_halta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gundelik halta',
                'verbose_name_plural': 'Gundelik haltalar',
            },
        ),
    ]
