# Generated by Django 3.1.7 on 2023-05-28 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0018_auto_20230522_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='sene',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='gelen_sklat',
            name='sene',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='giden_sklat',
            name='sene',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='sene',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='inwentar',
            name='sene',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='ojidanie',
            name='sene',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Senesi'),
        ),
    ]
