# Generated by Django 3.1.7 on 2023-05-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0019_auto_20230528_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equ_money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sene', models.DateField(blank=True, default='', null=True, verbose_name='Senesi')),
                ('dollar', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Dollar bahasy')),
                ('euro', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Euro bahasy')),
            ],
            options={
                'verbose_name': 'Equivalent',
                'verbose_name_plural': 'Equivalents',
            },
        ),
    ]
