# Generated by Django 3.1.7 on 2023-05-30 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0020_equ_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equ_money',
            name='sene',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi'),
        ),
    ]
