# Generated by Django 3.1.7 on 2023-06-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0021_auto_20230530_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwentar',
            name='sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Sany'),
        ),
    ]
