# Generated by Django 3.1.7 on 2023-06-02 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0023_auto_20230602_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='sene',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='gelen_sklat',
            name='sene',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='giden_sklat',
            name='sene',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='sene',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='inwentar',
            name='sene',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='ojidanie',
            name='sene',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi'),
        ),
    ]
