# Generated by Django 3.1.7 on 2023-06-04 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0024_auto_20230602_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aydaky_halta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_olceg', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Haltaň ölçegi')),
                ('jemi_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Jemi ayda haltaň sany')),
                ('jemi_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Jemi ayda haltaň kg')),
                ('abat_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Jemi ayda abat haltaň sany')),
                ('brak_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Jemi ayda brak haltaň sany')),
                ('algy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Jemi ayda algylar')),
                ('bergi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Jemi ayda bergiler')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
            ],
            options={
                'verbose_name': 'Ayda tikilen haltaň hasabaty',
                'verbose_name_plural': 'Ayda tikilen haltaň hasabatlar',
            },
        ),
        migrations.CreateModel(
            name='Halta_gornus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Haltaň görnüşi')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
            ],
            options={
                'verbose_name': 'Haltaň görnüşi',
                'verbose_name_plural': 'Haltaň görnüşleri',
            },
        ),
        migrations.CreateModel(
            name='Inwen_spisat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harydyn_ady', models.CharField(blank=True, max_length=500, null=True, verbose_name='Harydyň ady')),
                ('bahasy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bahasy')),
                ('sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Sany')),
                ('nirde_dur', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Haryt nirde dur')),
                ('bellik', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
            ],
            options={
                'verbose_name': 'Spisat edilen inwentar',
                'verbose_name_plural': 'Spisat edilen inwentarlar',
            },
        ),
        migrations.CreateModel(
            name='Sehe_paylamak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karhana', models.CharField(blank=True, max_length=500, null=True, verbose_name='Kärhanalar')),
                ('kim_eltipberdi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kim eltip berdi')),
                ('paddon', models.IntegerField(blank=True, default=None, null=True, verbose_name='Paddon sany')),
                ('big_bag', models.IntegerField(blank=True, default=None, null=True, verbose_name='Big bag halta sany')),
                ('arassa_agram', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sehe gelen arassa agram')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
            ],
            options={
                'verbose_name': 'Sehlere paýlanan çygmal',
                'verbose_name_plural': 'Sehlere paýlanan çygmallar',
            },
        ),
        migrations.CreateModel(
            name='World_cygmal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karhana', models.CharField(blank=True, max_length=500, null=True, verbose_name='Kärhanalar')),
                ('kontrak_nomer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şertnama belgisi')),
                ('markasy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Markasy')),
                ('tony', models.IntegerField(blank=True, default=None, null=True, verbose_name='Mukdary')),
                ('bahasy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bahasy')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
            ],
            options={
                'verbose_name': 'Daşary ýurt çigmal',
                'verbose_name_plural': 'Daşary ýurt çigmallar',
            },
        ),
        migrations.CreateModel(
            name='World_sklad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karhana', models.CharField(blank=True, max_length=500, null=True, verbose_name='Kärhanalar')),
                ('kontrak_nomer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şertnama belgisi')),
                ('markasy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Markasy')),
                ('tony', models.IntegerField(blank=True, default=None, null=True, verbose_name='Mukdary')),
                ('bahasy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bahasy')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
            ],
            options={
                'verbose_name': 'Daşary ýurt çigmal sklada gelen',
                'verbose_name_plural': 'Daşary ýurt çigmallar sklada gelen',
            },
        ),
        migrations.AlterModelOptions(
            name='gundelik_halta',
            options={'verbose_name': 'Gündelik halta', 'verbose_name_plural': 'Gündelik haltalar'},
        ),
        migrations.RemoveField(
            model_name='bolek_hasaplar',
            name='ostatok',
        ),
        migrations.RemoveField(
            model_name='gundelik_halta',
            name='h_gornusi',
        ),
        migrations.RemoveField(
            model_name='gundelik_halta',
            name='othod_kg',
        ),
        migrations.RemoveField(
            model_name='gundelik_halta',
            name='sarp_sapak',
        ),
        migrations.AddField(
            model_name='gundelik_halta',
            name='abathalta_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Abat haltaň bahasy'),
        ),
        migrations.AddField(
            model_name='gundelik_halta',
            name='brakhalta_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Brak haltaň bahasy'),
        ),
        migrations.AddField(
            model_name='gundelik_halta',
            name='ganarhalta_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ganar haltaň bahasy'),
        ),
        migrations.AddField(
            model_name='gundelik_halta',
            name='ganarhalta_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ganar haltan kg'),
        ),
        migrations.AddField(
            model_name='gundelik_halta',
            name='ganarhalta_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Ganar haltaň sany'),
        ),
        migrations.AddField(
            model_name='gundelik_halta',
            name='sarp_sapak_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Dikilyan halta gityan sapak kg'),
        ),
        migrations.AddField(
            model_name='gundelik_halta',
            name='wozwrat_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Wozwrat kg'),
        ),
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='sebap',
            field=models.CharField(blank=True, max_length=100, verbose_name='Girdejiniň ya-da çykdajynyň sebäbi'),
        ),
        migrations.AlterField(
            model_name='gir_ostatok',
            name='sene',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='abathalta_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Abat haltaň sany'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='enjam',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Haysy enjamda dokalan'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='h_olceg',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Haltaň ölçegi'),
        ),
    ]
