# Generated by Django 3.1.7 on 2023-06-05 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_other_users_sehler_wez_other'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shu', '0026_auto_20230604_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='aydaky_halta',
            name='beren_puly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Jemi ayda beren puly'),
        ),
        migrations.AddField(
            model_name='aydaky_halta',
            name='ganar_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Jemi ayda ganar haltaň sany'),
        ),
        migrations.AddField(
            model_name='aydaky_halta',
            name='jemi_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Jemi aydaky hardyn bahasy'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_halta', to='users.other_users'),
        ),
        migrations.AlterField(
            model_name='sehe_paylamak',
            name='karhana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler'),
        ),
        migrations.AlterField(
            model_name='world_cygmal',
            name='karhana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler'),
        ),
        migrations.AlterField(
            model_name='world_sklad',
            name='karhana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler'),
        ),
        migrations.CreateModel(
            name='Walyuta_hasap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasap', models.CharField(blank=True, max_length=100, null=True, verbose_name='Walýuta hasap')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('karhana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler')),
            ],
            options={
                'verbose_name': 'Walýuta hasap',
                'verbose_name_plural': 'Walýuta hasaplar',
            },
        ),
        migrations.CreateModel(
            name='Hasap_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gideji', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Girdeji')),
                ('cykdajy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Çykdajy')),
                ('ostatok', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ostatok')),
                ('sebap', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sebäbi')),
                ('bellik', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('wal_hasap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.walyuta_hasap')),
            ],
            options={
                'verbose_name': 'Walýuta hasap maglumat',
                'verbose_name_plural': 'Walýuta hasap maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='Halta_seh_ay_hasabat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oklady', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Oklady')),
                ('ay_isguni', models.IntegerField(blank=True, default=None, null=True, verbose_name='Aydaky iş güni')),
                ('gune_dusyan_haky', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Bir güne düşýän haky')),
                ('is_gun_sagady', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Iş gün sagady')),
                ('sagat_dusyan_haky', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Sagadyna düşýän haky')),
                ('is_gun_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Işlän gün sany')),
                ('artyk_is_sagady', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Artyk işlän sagasy')),
                ('awans', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Awans')),
                ('kart_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Kartyna geçýän summa')),
                ('el_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Eline almaly summa')),
                ('bellik', models.TextField(blank=True, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_sehayhasabat', to='users.other_users')),
            ],
            options={
                'verbose_name': 'Halta seh aýlyk hasabaty',
                'verbose_name_plural': 'Halta seh aýlyk hasabatlary',
            },
        ),
        migrations.CreateModel(
            name='Gunlikhalta_hasabat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_olceg', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Haltaň ölçegi')),
                ('gecenay_galyndy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Geçen galyndy')),
                ('jemi_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Jemi haltaň sany')),
                ('satylan_halta_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Jemi satylan haltaň sany')),
                ('wozwrat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Jemi wozwrat')),
                ('ahyrky_galyndy', models.IntegerField(blank=True, default=None, null=True, verbose_name='Jemi ahyrky galyndy sany')),
                ('yerinde_bar_haryt', models.IntegerField(blank=True, default=None, null=True, verbose_name='Jemi ýerinde bar harydyň sany')),
                ('tapawudy', models.IntegerField(blank=True, default=None, null=True, verbose_name='Tapawut')),
                ('bellik', models.TextField(blank=True, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('h_gornusi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.halta_gornus')),
            ],
            options={
                'verbose_name': 'Gündelik haltaň hasabaty',
                'verbose_name_plural': 'Gündelik haltaň hasabatlary',
            },
        ),
        migrations.CreateModel(
            name='Aylyk_premya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('summa_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi manat')),
                ('summa_dollar', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi dollarda')),
                ('sebap', models.CharField(blank=True, max_length=100, verbose_name='Jemi girdejileriniň sebäbi')),
                ('bellik', models.TextField(blank=True, verbose_name='Bellik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aylyk_premya', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aýlyk peýda premýa',
                'verbose_name_plural': 'Aýlyklar peýdalar premýalar',
            },
        ),
        migrations.CreateModel(
            name='Aydakyhalta_hasabat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_olceg', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Haltaň ölçegi')),
                ('gecenay_galyndy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Geçen aýdaky galyndy')),
                ('jemi_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Jemi aýdaky haltaň sany')),
                ('satylan_halta_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Jemi aýdaky satylan haltaň sany')),
                ('wozwrat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Jemi aýdaky wozwrat')),
                ('ahyrky_galyndy', models.IntegerField(blank=True, default=None, null=True, verbose_name='Jemi aýdaky ahyrky galyndy sany')),
                ('yerinde_bar_haryt', models.IntegerField(blank=True, default=None, null=True, verbose_name='Jemi aýdaky ýerinde bar harydyň sany')),
                ('tapawudy', models.IntegerField(blank=True, default=None, null=True, verbose_name='Aýdaky tapawut')),
                ('bellik', models.TextField(blank=True, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('h_gornusi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.halta_gornus')),
            ],
            options={
                'verbose_name': 'Aýdaky haltaň hasabaty',
                'verbose_name_plural': 'Aýdaky haltaň hasabatlary',
            },
        ),
    ]
