# Generated by Django 3.1.7 on 2023-06-06 13:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_other_users_sehler_wez_other'),
        ('shu', '0027_auto_20230605_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aydaky_halta',
            name='abat_sany',
        ),
        migrations.RemoveField(
            model_name='aydaky_halta',
            name='brak_sany',
        ),
        migrations.RemoveField(
            model_name='aydaky_halta',
            name='ganar_sany',
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='abathalta_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Abat haltaň kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='brakhalta_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Brak haltaň sany'),
        ),
        migrations.CreateModel(
            name='Zakaz_balans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balans', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Balans')),
                ('algy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Algy manat')),
                ('bergi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Bergi manat')),
                ('sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Harydyň sany')),
                ('bahasy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Harydyň bahasy')),
                ('gelen_cygmal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Gelen çygmal')),
                ('wozwrat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Çygmal wozwrat')),
                ('Bellik', models.CharField(blank=True, max_length=1000, verbose_name='Bellik')),
                ('zakaz_sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Haryt zakaz edilen senesi')),
                ('toleg_sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Haryt töleg edilen senesi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakaz_balans', to='users.other_users')),
            ],
            options={
                'verbose_name': 'Zakazçynyň balansy',
                'verbose_name_plural': 'Zakazçynyň balanslary',
            },
        ),
    ]
