# Generated by Django 3.1.7 on 2023-06-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0028_auto_20230606_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz_balans',
            name='toleg_sene',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Haryt töleg edilen senesi'),
        ),
    ]
