# Generated by Django 3.1.7 on 2023-06-07 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230607_0851'),
        ('shu', '0029_auto_20230607_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='gundelik_halta',
            name='zakaz_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.other_users'),
        ),
    ]
