# Generated by Django 3.1.7 on 2023-06-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0031_aydaky_halta_zakaz_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaz_balans',
            name='Bellik',
        ),
        migrations.AddField(
            model_name='zakaz_balans',
            name='bellik',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Bellik'),
        ),
    ]
