# Generated by Django 3.1.7 on 2023-06-13 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0034_auto_20230611_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz_balans',
            name='h_gornusi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.halta_gornus'),
        ),
        migrations.AddField(
            model_name='zakaz_balans',
            name='h_olceg',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Haltaň ölçegi'),
        ),
    ]
