# Generated by Django 3.1.7 on 2023-06-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0035_auto_20230613_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz_balans',
            name='h_olceg',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Önümiň ölçegi'),
        ),
    ]
