# Generated by Django 3.1.7 on 2023-06-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0037_zakaz_balans_haryt_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gundelik_halta',
            name='zakaz_code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Zakaz belgisi'),
        ),
        migrations.AddField(
            model_name='zakaz_balans',
            name='action',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Harydyň hereketi'),
        ),
    ]
