# Generated by Django 3.1.7 on 2023-06-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0038_auto_20230614_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz_balans',
            name='action',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Harydyň hereketi'),
        ),
    ]
