# Generated by Django 3.1.7 on 2023-06-15 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0039_auto_20230614_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gundelik_halta',
            name='zakaz_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.zakaz_balans'),
        ),
    ]
