# Generated by Django 3.1.7 on 2023-06-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0041_auto_20230615_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaz_balans',
            name='action',
        ),
        migrations.AddField(
            model_name='zakaz_balans',
            name='tolenen_pul',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tölän puly manat'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='katyska_agram',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Katuşkaň agramy kg'),
        ),
    ]
