# Generated by Django 3.1.7 on 2023-06-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0042_auto_20230616_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aydaky_halta',
            name='algy',
        ),
        migrations.RemoveField(
            model_name='aydaky_halta',
            name='beren_puly',
        ),
        migrations.RemoveField(
            model_name='aydaky_halta',
            name='bergi',
        ),
        migrations.AddField(
            model_name='aydaky_halta',
            name='zakaz_code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Zakaz belgisi'),
        ),
    ]
