# Generated by Django 3.1.7 on 2023-06-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0043_auto_20230619_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aydakyhalta_hasabat',
            name='gecenay_galyndy',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=6, null=True, verbose_name='Geçen aýdaky galyndy'),
        ),
    ]
