# Generated by Django 3.1.7 on 2023-06-21 11:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0044_auto_20230620_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hasabat_sene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
            ],
            options={
                'verbose_name': 'Ay sene',
                'verbose_name_plural': 'Aydaky seneler',
            },
        ),
        migrations.AddField(
            model_name='gundelik_halta',
            name='has_sene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.hasabat_sene'),
        ),
    ]
