# Generated by Django 3.1.7 on 2023-06-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0045_auto_20230621_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='has_sene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.hasabat_sene'),
        ),
    ]
