# Generated by Django 3.1.7 on 2023-06-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0046_aydakyhalta_hasabat_has_sene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gundelik_halta',
            name='has_sene',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Gornusi'),
        ),
    ]
