# Generated by Django 3.1.7 on 2023-06-24 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0048_auto_20230623_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaz_swotka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jemi_sany', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Jemi sany')),
                ('bahasy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Bahasy')),
                ('jemi_gir_baha', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Jemi girdeji bahasy')),
                ('cyk_summa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Jemi çykdaýjy')),
                ('cyk_summa_dol', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Jemi çykdaýjy walýuta')),
                ('gal_pey_summa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Jemi peýda')),
                ('gal_pey_summa_dol', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Jemi peýda walýuta')),
                ('bellik', models.TextField(blank=True, max_length=1000, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='senesi')),
            ],
            options={
                'verbose_name': 'Zakaz swotka',
                'verbose_name_plural': 'Zakaz swotkalar',
            },
        ),
    ]
