# Generated by Django 3.1.7 on 2023-06-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0049_zakaz_swotka'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz_swotka',
            name='sene_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Senesi id'),
        ),
    ]
