# Generated by Django 3.1.7 on 2023-06-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0051_auto_20230624_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz_swotka',
            name='jemi_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Harydyň sany'),
        ),
    ]
