# Generated by Django 4.2.1 on 2023-07-02 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_office_all_sehler_sehler_office'),
        ('shu', '0054_gundelik_halta_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='aydaky_halta',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ay_office', to='users.office'),
        ),
    ]
