# Generated by Django 4.2.1 on 2023-07-11 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_office_all_sehler_sehler_office'),
        ('shu', '0058_remove_zakaz_dokmaswotka_jemi_sany_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aydakysapak_hasabat',
            options={'verbose_name': 'Aýdaky dokalan sapak hasabaty (Tabel)', 'verbose_name_plural': 'Aýdaky dokalan sapak hasabatlary (Tabeller)'},
        ),
        migrations.AlterModelOptions(
            name='dokma_seh_ay_tabel',
            options={'verbose_name': 'Dokma seh aýlyk hasabaty (Tabel)', 'verbose_name_plural': 'Dokma seh aýlyk hasabatlary (Tabeller)'},
        ),
        migrations.AlterModelOptions(
            name='halta_seh_ay_tabel',
            options={'verbose_name': 'Halta seh aýlyk hasabaty (Tabel)', 'verbose_name_plural': 'Halta seh aýlyk hasabatlary (Tabeller)'},
        ),
        migrations.AddField(
            model_name='gundelik_dokma',
            name='sehs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_sehs', to='users.sehler'),
        ),
        migrations.AddField(
            model_name='gundelik_halta',
            name='sehs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h_sehs', to='users.sehler'),
        ),
        migrations.AddField(
            model_name='gundelik_sapak',
            name='sehs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_sehs', to='users.sehler'),
        ),
    ]
