# Generated by Django 4.2.1 on 2023-07-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0060_aydaky_dokma_sehs_aydaky_halta_sehs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aydakysklad_hasabat',
            name='olceg_birligi',
        ),
        migrations.RemoveField(
            model_name='gelen_sklat',
            name='olceg_birligi',
        ),
        migrations.RemoveField(
            model_name='giden_sklat',
            name='olceg_birligi',
        ),
        migrations.AddField(
            model_name='aydakysklad_hasabat',
            name='haryt_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Haryt kg'),
        ),
        migrations.AddField(
            model_name='gelen_sklat',
            name='haryt_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Haryt kg'),
        ),
        migrations.AddField(
            model_name='gelen_sklat',
            name='jemi_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi bahasy'),
        ),
        migrations.AddField(
            model_name='gelen_sklat',
            name='satlyk_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Satlyk düşýän bahasy'),
        ),
        migrations.AddField(
            model_name='giden_sklat',
            name='haryt_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Haryt kg'),
        ),
        migrations.AddField(
            model_name='giden_sklat',
            name='jemi_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi bahasy'),
        ),
        migrations.AddField(
            model_name='giden_sklat',
            name='satlyk_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Satlyk düşýän bahasy'),
        ),
    ]
