# Generated by Django 4.2.1 on 2023-07-13 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_cigmal_zawodlar'),
        ('shu', '0061_remove_aydakysklad_hasabat_olceg_birligi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alynan_haryt_pul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harydyn_ady', models.CharField(blank=True, max_length=500, null=True, verbose_name='Harydyň ady')),
                ('sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Harydyň sany')),
                ('haryt_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Haryt kg')),
                ('bahasy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bahasy manatda')),
                ('bahasy_dol', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bahasy dollarda')),
                ('jemi_bahasy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi bahasy manatda')),
                ('jemi_bahasy_d', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi bahasy dollarda')),
                ('bellik', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('has_sene', models.IntegerField(blank=True, default=None, null=True, verbose_name='Senesi')),
            ],
            options={
                'verbose_name': 'Alynan haryt ýa-da pul',
                'verbose_name_plural': 'Alynan harytlar ýa-da pullar',
            },
        ),
        migrations.CreateModel(
            name='Berilen_haryt_pul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harydyn_ady', models.CharField(blank=True, max_length=500, null=True, verbose_name='Harydyň ady')),
                ('sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Harydyň sany')),
                ('haryt_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Haryt kg')),
                ('bahasy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bahasy manatda')),
                ('bahasy_dol', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bahasy dollarda')),
                ('jemi_bahasy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi bahasy manatda')),
                ('jemi_bahasy_d', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi bahasy dollarda')),
                ('bellik', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('has_sene', models.IntegerField(blank=True, default=None, null=True, verbose_name='Senesi')),
            ],
            options={
                'verbose_name': 'Berilen haryt ýa-da pul',
                'verbose_name_plural': 'Berilen harytlar ýa-da pullar',
            },
        ),
        migrations.CreateModel(
            name='Das_isleyan_zawod_tapawut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harydyn_ady', models.CharField(blank=True, max_length=500, null=True, verbose_name='Harydyň ady')),
                ('sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Harydyň sany')),
                ('haryt_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Haryt kg')),
                ('jemi_bahasy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi bahasy manatda')),
                ('jemi_bahasy_d', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi bahasy dollarda')),
                ('tapawudy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi tapawut bahasy manatda')),
                ('tapawudy_d', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi tapawut bahasy dollarda')),
                ('bellik', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('has_sene', models.IntegerField(blank=True, default=None, null=True, verbose_name='Senesi')),
            ],
            options={
                'verbose_name': 'Berilen haryt ýa-da pul',
                'verbose_name_plural': 'Berilen harytlar ýa-da pullar',
            },
        ),
        migrations.AlterModelOptions(
            name='world_cygmal',
            options={'verbose_name': 'Zawotdan alynan çigmal', 'verbose_name_plural': 'Zawotdan alynan çigmallar'},
        ),
        migrations.AlterModelOptions(
            name='world_sklad',
            options={'verbose_name': 'Daşyndan sklada gelen çigmal', 'verbose_name_plural': 'Daşyndan sklada gelen çigmallar'},
        ),
        migrations.RemoveField(
            model_name='world_cygmal',
            name='karhana',
        ),
        migrations.RemoveField(
            model_name='world_sklad',
            name='karhana',
        ),
        migrations.AddField(
            model_name='world_cygmal',
            name='bellik',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Bellik'),
        ),
        migrations.AddField(
            model_name='world_cygmal',
            name='zawod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cigmal_zawodlar'),
        ),
        migrations.AddField(
            model_name='world_sklad',
            name='bellik',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Bellik'),
        ),
        migrations.AddField(
            model_name='world_sklad',
            name='zawod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cigmal_zawodlar'),
        ),
        migrations.AlterField(
            model_name='world_cygmal',
            name='tony',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Mukdary'),
        ),
    ]
