# Generated by Django 4.2.1 on 2023-07-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0062_alynan_haryt_pul_berilen_haryt_pul_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='world_cygmal',
            name='bahasy',
        ),
        migrations.RemoveField(
            model_name='world_sklad',
            name='bahasy',
        ),
        migrations.AddField(
            model_name='world_cygmal',
            name='bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bahasy dollarda'),
        ),
        migrations.AddField(
            model_name='world_cygmal',
            name='bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bahasy manatda'),
        ),
        migrations.AddField(
            model_name='world_sklad',
            name='bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bahasy dollarda'),
        ),
        migrations.AddField(
            model_name='world_sklad',
            name='bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bahasy manatda'),
        ),
    ]
