# Generated by Django 4.2.1 on 2023-07-13 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0063_remove_world_cygmal_bahasy_remove_world_sklad_bahasy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='world_sklad',
            name='kimden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.world_cygmal'),
        ),
    ]
