# Generated by Django 4.2.1 on 2023-07-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_cigmal_zawodlar'),
        ('shu', '0064_world_sklad_kimden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='world_cygmal',
            options={'verbose_name': 'Zawotdan satyn alynan çigmal', 'verbose_name_plural': 'Zawotdan satyn alynan çigmallar'},
        ),
        migrations.RemoveField(
            model_name='world_sklad',
            name='kimden',
        ),
        migrations.AddField(
            model_name='world_sklad',
            name='kime_dusdi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler'),
        ),
    ]
