# Generated by Django 4.2.1 on 2023-07-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0065_alter_world_cygmal_options_remove_world_sklad_kimden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gelen_sklat',
            name='jemi_bahasy',
        ),
        migrations.RemoveField(
            model_name='gelen_sklat',
            name='oz_bahasy',
        ),
        migrations.RemoveField(
            model_name='gelen_sklat',
            name='satlyk_bahasy',
        ),
        migrations.RemoveField(
            model_name='giden_sklat',
            name='jemi_bahasy',
        ),
        migrations.RemoveField(
            model_name='giden_sklat',
            name='nirden_gelen',
        ),
        migrations.RemoveField(
            model_name='giden_sklat',
            name='oz_bahasy',
        ),
        migrations.RemoveField(
            model_name='giden_sklat',
            name='satlyk_bahasy',
        ),
        migrations.AddField(
            model_name='gelen_sklat',
            name='oz_bahasy_dol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Özüne düşýän bahasy $'),
        ),
        migrations.AddField(
            model_name='gelen_sklat',
            name='oz_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Özüne düşýän bahasy TMT'),
        ),
        migrations.AddField(
            model_name='gelen_sklat',
            name='satlyk_bahasy_dol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Satlyk düşýän bahasy $'),
        ),
        migrations.AddField(
            model_name='gelen_sklat',
            name='satlyk_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Satlyk düşýän bahasy TMT'),
        ),
        migrations.AddField(
            model_name='giden_sklat',
            name='nira_gitdi',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='haryt nirä gitdi'),
        ),
        migrations.AddField(
            model_name='giden_sklat',
            name='oz_bahasy_dol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Özüne düşýän bahasy $'),
        ),
        migrations.AddField(
            model_name='giden_sklat',
            name='oz_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Özüne düşýän bahasy TMT'),
        ),
        migrations.AddField(
            model_name='giden_sklat',
            name='satlyk_bahasy_dol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Satlyk düşýän bahasy $'),
        ),
        migrations.AddField(
            model_name='giden_sklat',
            name='satlyk_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Satlyk düşýän bahasy TMT'),
        ),
    ]
