# Generated by Django 4.2.1 on 2023-07-16 08:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_cigmal_zawodlar'),
        ('shu', '0066_remove_gelen_sklat_jemi_bahasy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='world_cygmal',
            name='bigbag_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Big bag kg'),
        ),
        migrations.AddField(
            model_name='world_cygmal',
            name='paddon_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Paddon kg'),
        ),
        migrations.AddField(
            model_name='world_sklad',
            name='bigbag_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Big bag kg'),
        ),
        migrations.AddField(
            model_name='world_sklad',
            name='paddon_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Paddon kg'),
        ),
        migrations.AlterField(
            model_name='gelen_sklat',
            name='modeli',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Modeli'),
        ),
        migrations.AlterField(
            model_name='gelen_sklat',
            name='nirden_gelen',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Haryt nirden geldi'),
        ),
        migrations.AlterField(
            model_name='gelen_sklat',
            name='satlyk_bahasy_dol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Satlyk bahasy $'),
        ),
        migrations.AlterField(
            model_name='gelen_sklat',
            name='satlyk_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Satlyk bahasy TMT'),
        ),
        migrations.AlterField(
            model_name='giden_sklat',
            name='nira_gitdi',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Haryt nirä gitdi'),
        ),
        migrations.AlterField(
            model_name='giden_sklat',
            name='satlyk_bahasy_dol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Satlyk bahasy $'),
        ),
        migrations.AlterField(
            model_name='giden_sklat',
            name='satlyk_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Satlyk bahasy TMT'),
        ),
        migrations.CreateModel(
            name='Sklad_swotkalar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontrak_nomer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şertnama belgisi')),
                ('markasy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Markasy')),
                ('gelen_tony', models.IntegerField(blank=True, default=None, null=True, verbose_name='Harydyň gelen sany')),
                ('giden_tony', models.IntegerField(blank=True, default=None, null=True, verbose_name='Harydyň giden sany')),
                ('gelen_bahasy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Gelende özüne düşýän bahasy TMT')),
                ('giden_bahasy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Gidende özüne düşýän bahasy TMT')),
                ('gelen_bahasy_d', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Gelende özüne düşýän bahasy $')),
                ('giden_bahasy_d', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Gidende özüne düşýän bahasy $')),
                ('galyndy_bahasy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Galyndy bahasy TMT')),
                ('galyndy_bahasy_d', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Galyndy bahasy $')),
                ('galyndy_tony', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Galyndy kg')),
                ('paddon_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Paddon kg')),
                ('bigbag_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Big bag kg')),
                ('gel_sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Alynan senesi')),
                ('gid_sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Gelen senesi')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('bellik', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Bellik')),
                ('has_sene', models.IntegerField(blank=True, default=None, null=True, verbose_name='Senesi')),
                ('kimden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cigmal_zawodlar')),
                ('kime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler')),
            ],
            options={
                'verbose_name': 'Daşyndan alynan we gelen çigmalyň swotkasy',
                'verbose_name_plural': 'Daşyndan alynan we gelen çigmallaryň swotkasy',
            },
        ),
    ]
