# Generated by Django 4.2.1 on 2023-07-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0068_rename_gelen_bahasy_d_sklad_swotkalar_bahasy_d_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sklad_swotkalar',
            name='gid_sene',
        ),
        migrations.AddField(
            model_name='sklad_swotkalar',
            name='j_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi bahasy dollarda'),
        ),
        migrations.AddField(
            model_name='sklad_swotkalar',
            name='j_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi bahasy manatda'),
        ),
        migrations.AddField(
            model_name='world_cygmal',
            name='j_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi bahasy dollarda'),
        ),
        migrations.AddField(
            model_name='world_cygmal',
            name='j_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi bahasy manatda'),
        ),
        migrations.AddField(
            model_name='world_sklad',
            name='j_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi bahasy dollarda'),
        ),
        migrations.AddField(
            model_name='world_sklad',
            name='j_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi bahasy manatda'),
        ),
    ]
