# Generated by Django 4.2.1 on 2023-07-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0069_remove_sklad_swotkalar_gid_sene_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad_swotkalar',
            name='j_gel_bah_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi gelen bahasy dollarda'),
        ),
        migrations.AddField(
            model_name='sklad_swotkalar',
            name='j_gel_bah_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi gelen bahasy manatda'),
        ),
        migrations.AlterField(
            model_name='sklad_swotkalar',
            name='j_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi alynan bahasy dollarda'),
        ),
        migrations.AlterField(
            model_name='sklad_swotkalar',
            name='j_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Jemi alynanbahasy manatda'),
        ),
    ]
