# Generated by Django 4.2.2 on 2023-07-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0070_sklad_swotkalar_j_gel_bah_d_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aydakysklad_hasabat',
            name='jemi_gelen',
        ),
        migrations.RemoveField(
            model_name='aydakysklad_hasabat',
            name='jemi_giden',
        ),
        migrations.RemoveField(
            model_name='aydakysklad_hasabat',
            name='sany',
        ),
        migrations.AddField(
            model_name='aydakysklad_hasabat',
            name='jemi_gelen_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Jemi aýdaky gelen bahasy $'),
        ),
        migrations.AddField(
            model_name='aydakysklad_hasabat',
            name='jemi_gelen_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Jemi aýdaky gelen bahasy TMT'),
        ),
        migrations.AddField(
            model_name='aydakysklad_hasabat',
            name='jemi_giden_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Jemi aýdaky giden bahasy $'),
        ),
        migrations.AddField(
            model_name='aydakysklad_hasabat',
            name='jemi_giden_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Jemi aýdaky giden bahasy TMT'),
        ),
        migrations.AddField(
            model_name='aydakysklad_hasabat',
            name='jemi_sany',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Harydyň mukdary'),
        ),
        migrations.AddField(
            model_name='gelen_sklat',
            name='jemi_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Harydyň jemi bahasy $'),
        ),
        migrations.AddField(
            model_name='gelen_sklat',
            name='jemi_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Harydyň jemi bahasy TMT'),
        ),
        migrations.AddField(
            model_name='giden_sklat',
            name='jemi_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Harydyň jemi bahasy $'),
        ),
        migrations.AddField(
            model_name='giden_sklat',
            name='jemi_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Harydyň jemi bahasy TMT'),
        ),
        migrations.AlterField(
            model_name='aydakysklad_hasabat',
            name='ahyrky_galyndy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Jemi aýdaky ahyrky galyndy kg'),
        ),
        migrations.AlterField(
            model_name='aydakysklad_hasabat',
            name='tapawudy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Aýdaky tapawut'),
        ),
        migrations.AlterField(
            model_name='aydakysklad_hasabat',
            name='yerinde_bar_haryt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Jemi aýdaky ýerinde bar harydyň kg'),
        ),
    ]
