# Generated by Django 4.2.2 on 2023-07-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0071_remove_aydakysklad_hasabat_jemi_gelen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aydakysklad_hasabat',
            name='haryt_kg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Haryt kg'),
        ),
        migrations.AlterField(
            model_name='gelen_sklat',
            name='haryt_kg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Haryt kg'),
        ),
        migrations.AlterField(
            model_name='giden_sklat',
            name='haryt_kg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Haryt kg'),
        ),
    ]
