# Generated by Django 4.2.2 on 2023-07-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0072_alter_aydakysklad_hasabat_haryt_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gelen_sklat',
            name='jemi_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Harydyň jemi bahasy $'),
        ),
        migrations.AlterField(
            model_name='gelen_sklat',
            name='jemi_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Harydyň jemi bahasy TMT'),
        ),
        migrations.AlterField(
            model_name='gelen_sklat',
            name='oz_bahasy_dol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Özüne düşýän bahasy $'),
        ),
        migrations.AlterField(
            model_name='gelen_sklat',
            name='oz_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Özüne düşýän bahasy TMT'),
        ),
        migrations.AlterField(
            model_name='gelen_sklat',
            name='satlyk_bahasy_dol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Satlyk bahasy $'),
        ),
        migrations.AlterField(
            model_name='gelen_sklat',
            name='satlyk_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Satlyk bahasy TMT'),
        ),
    ]
