# Generated by Django 4.2.2 on 2023-07-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0073_alter_gelen_sklat_jemi_bahasy_d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aydakysklad_hasabat',
            name='ahyrky_galyndy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky ahyrky galyndy kg'),
        ),
        migrations.AlterField(
            model_name='aydakysklad_hasabat',
            name='gecenay_galyndy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Geçen aýdaky galyndy'),
        ),
        migrations.AlterField(
            model_name='aydakysklad_hasabat',
            name='jemi_gelen_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky gelen bahasy $'),
        ),
        migrations.AlterField(
            model_name='aydakysklad_hasabat',
            name='jemi_gelen_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky gelen bahasy TMT'),
        ),
        migrations.AlterField(
            model_name='aydakysklad_hasabat',
            name='jemi_giden_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky giden bahasy $'),
        ),
        migrations.AlterField(
            model_name='aydakysklad_hasabat',
            name='jemi_giden_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky giden bahasy TMT'),
        ),
        migrations.AlterField(
            model_name='aydakysklad_hasabat',
            name='jemi_sany',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Harydyň mukdary'),
        ),
        migrations.AlterField(
            model_name='aydakysklad_hasabat',
            name='tapawudy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Aýdaky tapawut'),
        ),
        migrations.AlterField(
            model_name='aydakysklad_hasabat',
            name='wozwrat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky wozwrat kg'),
        ),
        migrations.AlterField(
            model_name='aydakysklad_hasabat',
            name='yerinde_bar_haryt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky ýerinde bar harydyň kg'),
        ),
        migrations.AlterField(
            model_name='giden_sklat',
            name='jemi_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Harydyň jemi bahasy $'),
        ),
        migrations.AlterField(
            model_name='giden_sklat',
            name='jemi_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Harydyň jemi bahasy TMT'),
        ),
        migrations.AlterField(
            model_name='giden_sklat',
            name='oz_bahasy_dol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Özüne düşýän bahasy $'),
        ),
        migrations.AlterField(
            model_name='giden_sklat',
            name='oz_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Özüne düşýän bahasy TMT'),
        ),
        migrations.AlterField(
            model_name='giden_sklat',
            name='satlyk_bahasy_dol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Satlyk bahasy $'),
        ),
        migrations.AlterField(
            model_name='giden_sklat',
            name='satlyk_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Satlyk bahasy TMT'),
        ),
    ]
