# Generated by Django 4.2.1 on 2023-07-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0074_alter_aydakysklad_hasabat_ahyrky_galyndy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aydakysklad_hasabat',
            name='haryt_kg',
        ),
        migrations.RemoveField(
            model_name='gelen_sklat',
            name='haryt_kg',
        ),
        migrations.RemoveField(
            model_name='giden_sklat',
            name='haryt_kg',
        ),
        migrations.AddField(
            model_name='bolek_hasaplar',
            name='awans',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Awans'),
        ),
        migrations.AlterField(
            model_name='alynan_haryt_pul',
            name='bahasy_dol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bahasy dollarda'),
        ),
        migrations.AlterField(
            model_name='alynan_haryt_pul',
            name='bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bahasy manatda'),
        ),
        migrations.AlterField(
            model_name='alynan_haryt_pul',
            name='haryt_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Haryt kg'),
        ),
        migrations.AlterField(
            model_name='alynan_haryt_pul',
            name='jemi_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy dollarda'),
        ),
        migrations.AlterField(
            model_name='alynan_haryt_pul',
            name='jemi_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy manatda'),
        ),
        migrations.AlterField(
            model_name='aydaky_dokma',
            name='jemi_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aydaky rulonyň bahasy'),
        ),
        migrations.AlterField(
            model_name='aydaky_dokma',
            name='jemi_cyk_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi ayda çykan rulonyň kg'),
        ),
        migrations.AlterField(
            model_name='aydaky_halta',
            name='jemi_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aydaky hardyn bahasy'),
        ),
        migrations.AlterField(
            model_name='aydaky_halta',
            name='jemi_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi ayda haltaň kg'),
        ),
        migrations.AlterField(
            model_name='aydaky_sapak',
            name='jemi_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aydaky sapagyň bahasy'),
        ),
        migrations.AlterField(
            model_name='aydaky_sapak',
            name='jemi_cyk_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aydaky sapagyň kg'),
        ),
        migrations.AlterField(
            model_name='aydakydokma_hasabat',
            name='ahyrky_galyndy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky ahyrky galyndy kg'),
        ),
        migrations.AlterField(
            model_name='aydakydokma_hasabat',
            name='gecenay_galyndy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Geçen aýdaky galyndy'),
        ),
        migrations.AlterField(
            model_name='aydakydokma_hasabat',
            name='jemi_dok_rulon',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky dokalan rulonyň kg'),
        ),
        migrations.AlterField(
            model_name='aydakydokma_hasabat',
            name='satylan_dokma_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky satylan dokmanyň kg'),
        ),
        migrations.AlterField(
            model_name='aydakydokma_hasabat',
            name='tapawudy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Aýdaky tapawut'),
        ),
        migrations.AlterField(
            model_name='aydakydokma_hasabat',
            name='wozwrat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky wozwrat'),
        ),
        migrations.AlterField(
            model_name='aydakydokma_hasabat',
            name='yerinde_bar_haryt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky ýerinde bar harydyň kg'),
        ),
        migrations.AlterField(
            model_name='aydakyhalta_hasabat',
            name='gecenay_galyndy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Geçen aýdaky galyndy'),
        ),
        migrations.AlterField(
            model_name='aydakyhalta_hasabat',
            name='wozwrat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky wozwrat'),
        ),
        migrations.AlterField(
            model_name='aydakysapak_hasabat',
            name='ahyrky_galyndy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky ahyrky galyndy kg'),
        ),
        migrations.AlterField(
            model_name='aydakysapak_hasabat',
            name='gecenay_galyndy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Geçen aýdaky galyndy'),
        ),
        migrations.AlterField(
            model_name='aydakysapak_hasabat',
            name='jemi_dok_sapak',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky sapagyň kg'),
        ),
        migrations.AlterField(
            model_name='aydakysapak_hasabat',
            name='satylan_sapak_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky satylan sapagyň kg'),
        ),
        migrations.AlterField(
            model_name='aydakysapak_hasabat',
            name='tapawudy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Aýdaky tapawut'),
        ),
        migrations.AlterField(
            model_name='aydakysapak_hasabat',
            name='wozwrat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky wozwrat kg'),
        ),
        migrations.AlterField(
            model_name='aydakysapak_hasabat',
            name='yerinde_bar_haryt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky ýerinde bar harydyň kg'),
        ),
        migrations.AlterField(
            model_name='aylyk_premya',
            name='summa_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi dollarda'),
        ),
        migrations.AlterField(
            model_name='aylyk_premya',
            name='summa_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi manat'),
        ),
        migrations.AlterField(
            model_name='berilen_haryt_pul',
            name='bahasy_dol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bahasy dollarda'),
        ),
        migrations.AlterField(
            model_name='berilen_haryt_pul',
            name='bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bahasy manatda'),
        ),
        migrations.AlterField(
            model_name='berilen_haryt_pul',
            name='haryt_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Haryt kg'),
        ),
        migrations.AlterField(
            model_name='berilen_haryt_pul',
            name='jemi_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy dollarda'),
        ),
        migrations.AlterField(
            model_name='berilen_haryt_pul',
            name='jemi_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy manatda'),
        ),
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='cykdajy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Her günüň çykdajysy'),
        ),
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='cykdajy_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Her günüň çykdajysy dollarda'),
        ),
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='girdeji',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Her günüň girdejisi'),
        ),
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='girdeji_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Her günüň girdejisi dollarda'),
        ),
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='kurs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='$ kursy'),
        ),
        migrations.AlterField(
            model_name='customer_account',
            name='algy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Algy manat'),
        ),
        migrations.AlterField(
            model_name='customer_account',
            name='bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Harydyň bahasy'),
        ),
        migrations.AlterField(
            model_name='customer_account',
            name='balans',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Balans'),
        ),
        migrations.AlterField(
            model_name='customer_account',
            name='bergi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bergi manat'),
        ),
        migrations.AlterField(
            model_name='customer_account',
            name='gelen_cygmal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Gelen çygmal'),
        ),
        migrations.AlterField(
            model_name='customer_account',
            name='tolenen_pul',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Tölän puly manat'),
        ),
        migrations.AlterField(
            model_name='customer_account',
            name='wozwrat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Çygmal wozwrat'),
        ),
        migrations.AlterField(
            model_name='customer_accountsapak',
            name='algy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Algy manat'),
        ),
        migrations.AlterField(
            model_name='customer_accountsapak',
            name='bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Harydyň bahasy'),
        ),
        migrations.AlterField(
            model_name='customer_accountsapak',
            name='balans',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Balans'),
        ),
        migrations.AlterField(
            model_name='customer_accountsapak',
            name='bergi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bergi manat'),
        ),
        migrations.AlterField(
            model_name='customer_accountsapak',
            name='gelen_cygmal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Gelen çygmal'),
        ),
        migrations.AlterField(
            model_name='customer_accountsapak',
            name='tolenen_pul',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Tölän puly manat'),
        ),
        migrations.AlterField(
            model_name='customer_accountsapak',
            name='wozwrat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Çygmal wozwrat'),
        ),
        migrations.AlterField(
            model_name='das_isleyan_zawod_tapawut',
            name='haryt_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Haryt kg'),
        ),
        migrations.AlterField(
            model_name='das_isleyan_zawod_tapawut',
            name='jemi_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy dollarda'),
        ),
        migrations.AlterField(
            model_name='das_isleyan_zawod_tapawut',
            name='jemi_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy manatda'),
        ),
        migrations.AlterField(
            model_name='das_isleyan_zawod_tapawut',
            name='tapawudy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi tapawut bahasy dollarda'),
        ),
        migrations.AlterField(
            model_name='das_isleyan_zawod_tapawut',
            name='tapawudy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi tapawut bahasy manatda'),
        ),
        migrations.AlterField(
            model_name='dokma_seh_ay_tabel',
            name='artyk_is_sagady',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Artyk işlän sagasy'),
        ),
        migrations.AlterField(
            model_name='dokma_seh_ay_tabel',
            name='awans',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Awans'),
        ),
        migrations.AlterField(
            model_name='dokma_seh_ay_tabel',
            name='el_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Eline almaly summa'),
        ),
        migrations.AlterField(
            model_name='dokma_seh_ay_tabel',
            name='gune_dusyan_haky',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bir güne düşýän haky'),
        ),
        migrations.AlterField(
            model_name='dokma_seh_ay_tabel',
            name='is_gun_sagady',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Iş gün sagady'),
        ),
        migrations.AlterField(
            model_name='dokma_seh_ay_tabel',
            name='kart_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Kartyna geçýän summa'),
        ),
        migrations.AlterField(
            model_name='dokma_seh_ay_tabel',
            name='oklady',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Oklady'),
        ),
        migrations.AlterField(
            model_name='dokma_seh_ay_tabel',
            name='sagat_dusyan_haky',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Sagadyna düşýän haky'),
        ),
        migrations.AlterField(
            model_name='equ_money',
            name='dollar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Dollar bahasy'),
        ),
        migrations.AlterField(
            model_name='equ_money',
            name='euro',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Euro bahasy'),
        ),
        migrations.AlterField(
            model_name='gir_ostatok',
            name='ostatok',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Her günüň ostatogy'),
        ),
        migrations.AlterField(
            model_name='gundelik_dokma',
            name='cykrulon_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Çykan rulonyň bahasy'),
        ),
        migrations.AlterField(
            model_name='gundelik_dokma',
            name='cykrulon_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Çykan rulonyň kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_dokma',
            name='katyska_agram',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Katuşkaň agramy kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_dokma',
            name='wozwrat_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Wozwrat kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='abathalta_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Abat haltaň bahasy'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='abathalta_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Abat haltaň kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='brakhalta_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Brak haltaň bahasy'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='brakhalta_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Brak haltan kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='ganarhalta_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Ganar haltaň bahasy'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='ganarhalta_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Ganar haltan kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='katyska_agram',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Katuşkaň agramy kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='sarp_sapak_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Dikilyan halta gityan sapak kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='wozwrat_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Wozwrat kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_sapak',
            name='cyksapak_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Çykan sapagyň bahasy'),
        ),
        migrations.AlterField(
            model_name='gundelik_sapak',
            name='cyksapak_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Çykan sapak kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_sapak',
            name='katyska_agram',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Katuşkaň agramy kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_sapak',
            name='wozwrat_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Wozwrat kg'),
        ),
        migrations.AlterField(
            model_name='halta_seh_ay_tabel',
            name='artyk_is_sagady',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Artyk işlän sagasy'),
        ),
        migrations.AlterField(
            model_name='halta_seh_ay_tabel',
            name='awans',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Awans'),
        ),
        migrations.AlterField(
            model_name='halta_seh_ay_tabel',
            name='el_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Eline almaly summa'),
        ),
        migrations.AlterField(
            model_name='halta_seh_ay_tabel',
            name='gune_dusyan_haky',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bir güne düşýän haky'),
        ),
        migrations.AlterField(
            model_name='halta_seh_ay_tabel',
            name='is_gun_sagady',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Iş gün sagady'),
        ),
        migrations.AlterField(
            model_name='halta_seh_ay_tabel',
            name='kart_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Kartyna geçýän summa'),
        ),
        migrations.AlterField(
            model_name='halta_seh_ay_tabel',
            name='oklady',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Oklady'),
        ),
        migrations.AlterField(
            model_name='halta_seh_ay_tabel',
            name='sagat_dusyan_haky',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Sagadyna düşýän haky'),
        ),
        migrations.AlterField(
            model_name='hasap_detail',
            name='cykdajy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Çykdajy'),
        ),
        migrations.AlterField(
            model_name='hasap_detail',
            name='gideji',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Girdeji'),
        ),
        migrations.AlterField(
            model_name='hasap_detail',
            name='ostatok',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Ostatok'),
        ),
        migrations.AlterField(
            model_name='inwen_spisat',
            name='bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bahasy'),
        ),
        migrations.AlterField(
            model_name='inwentar',
            name='bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bahasy'),
        ),
        migrations.AlterField(
            model_name='ojidanie',
            name='cash',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Nagt pul'),
        ),
        migrations.AlterField(
            model_name='sapak_seh_ay_tabel',
            name='artyk_is_sagady',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Artyk işlän sagasy'),
        ),
        migrations.AlterField(
            model_name='sapak_seh_ay_tabel',
            name='awans',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Awans'),
        ),
        migrations.AlterField(
            model_name='sapak_seh_ay_tabel',
            name='el_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Eline almaly summa'),
        ),
        migrations.AlterField(
            model_name='sapak_seh_ay_tabel',
            name='gune_dusyan_haky',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bir güne düşýän haky'),
        ),
        migrations.AlterField(
            model_name='sapak_seh_ay_tabel',
            name='is_gun_sagady',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Iş gün sagady'),
        ),
        migrations.AlterField(
            model_name='sapak_seh_ay_tabel',
            name='kart_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Kartyna geçýän summa'),
        ),
        migrations.AlterField(
            model_name='sapak_seh_ay_tabel',
            name='oklady',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Oklady'),
        ),
        migrations.AlterField(
            model_name='sapak_seh_ay_tabel',
            name='sagat_dusyan_haky',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Sagadyna düşýän haky'),
        ),
        migrations.AlterField(
            model_name='sehe_paylamak',
            name='arassa_agram',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Sehe gelen arassa agram'),
        ),
        migrations.AlterField(
            model_name='sklad_swotkalar',
            name='bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Gelende özüne düşýän bahasy $'),
        ),
        migrations.AlterField(
            model_name='sklad_swotkalar',
            name='bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Gelende özüne düşýän bahasy TMT'),
        ),
        migrations.AlterField(
            model_name='sklad_swotkalar',
            name='bigbag_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Big bag kg'),
        ),
        migrations.AlterField(
            model_name='sklad_swotkalar',
            name='galyndy_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Galyndy bahasy $'),
        ),
        migrations.AlterField(
            model_name='sklad_swotkalar',
            name='galyndy_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Galyndy bahasy TMT'),
        ),
        migrations.AlterField(
            model_name='sklad_swotkalar',
            name='galyndy_tony',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Galyndy kg'),
        ),
        migrations.AlterField(
            model_name='sklad_swotkalar',
            name='j_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi alynan bahasy dollarda'),
        ),
        migrations.AlterField(
            model_name='sklad_swotkalar',
            name='j_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi alynanbahasy manatda'),
        ),
        migrations.AlterField(
            model_name='sklad_swotkalar',
            name='j_gel_bah_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi gelen bahasy dollarda'),
        ),
        migrations.AlterField(
            model_name='sklad_swotkalar',
            name='j_gel_bah_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi gelen bahasy manatda'),
        ),
        migrations.AlterField(
            model_name='sklad_swotkalar',
            name='paddon_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Paddon kg'),
        ),
        migrations.AlterField(
            model_name='world_cygmal',
            name='bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bahasy dollarda'),
        ),
        migrations.AlterField(
            model_name='world_cygmal',
            name='bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bahasy manatda'),
        ),
        migrations.AlterField(
            model_name='world_cygmal',
            name='bigbag_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Big bag kg'),
        ),
        migrations.AlterField(
            model_name='world_cygmal',
            name='j_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy dollarda'),
        ),
        migrations.AlterField(
            model_name='world_cygmal',
            name='j_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy manatda'),
        ),
        migrations.AlterField(
            model_name='world_cygmal',
            name='paddon_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Paddon kg'),
        ),
        migrations.AlterField(
            model_name='world_cygmal',
            name='tony',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Mukdary'),
        ),
        migrations.AlterField(
            model_name='world_sklad',
            name='bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bahasy dollarda'),
        ),
        migrations.AlterField(
            model_name='world_sklad',
            name='bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bahasy manatda'),
        ),
        migrations.AlterField(
            model_name='world_sklad',
            name='bigbag_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Big bag kg'),
        ),
        migrations.AlterField(
            model_name='world_sklad',
            name='j_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy dollarda'),
        ),
        migrations.AlterField(
            model_name='world_sklad',
            name='j_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy manatda'),
        ),
        migrations.AlterField(
            model_name='world_sklad',
            name='paddon_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Paddon kg'),
        ),
        migrations.AlterField(
            model_name='zakaz_balans',
            name='algy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Algy manat'),
        ),
        migrations.AlterField(
            model_name='zakaz_balans',
            name='bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Harydyň bahasy'),
        ),
        migrations.AlterField(
            model_name='zakaz_balans',
            name='balans',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Balans'),
        ),
        migrations.AlterField(
            model_name='zakaz_balans',
            name='bergi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bergi manat'),
        ),
        migrations.AlterField(
            model_name='zakaz_balans',
            name='gelen_cygmal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Gelen çygmal'),
        ),
        migrations.AlterField(
            model_name='zakaz_balans',
            name='tolenen_pul',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Tölän puly manat'),
        ),
        migrations.AlterField(
            model_name='zakaz_balans',
            name='wozwrat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Çygmal wozwrat'),
        ),
        migrations.AlterField(
            model_name='zakaz_dokmaswotka',
            name='bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bahasy'),
        ),
        migrations.AlterField(
            model_name='zakaz_dokmaswotka',
            name='cyk_summa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi çykdaýjy'),
        ),
        migrations.AlterField(
            model_name='zakaz_dokmaswotka',
            name='cyk_summa_dol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi çykdaýjy walýuta'),
        ),
        migrations.AlterField(
            model_name='zakaz_dokmaswotka',
            name='gal_pey_summa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi peýda'),
        ),
        migrations.AlterField(
            model_name='zakaz_dokmaswotka',
            name='gal_pey_summa_dol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi peýda walýuta'),
        ),
        migrations.AlterField(
            model_name='zakaz_dokmaswotka',
            name='jemi_gir_baha',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi girdeji bahasy'),
        ),
        migrations.AlterField(
            model_name='zakaz_dokmaswotka',
            name='jemi_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Harydyň kg'),
        ),
        migrations.AlterField(
            model_name='zakaz_sapakswotka',
            name='bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bahasy'),
        ),
        migrations.AlterField(
            model_name='zakaz_sapakswotka',
            name='cyk_summa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi çykdaýjy'),
        ),
        migrations.AlterField(
            model_name='zakaz_sapakswotka',
            name='cyk_summa_dol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi çykdaýjy walýuta'),
        ),
        migrations.AlterField(
            model_name='zakaz_sapakswotka',
            name='gal_pey_summa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi peýda'),
        ),
        migrations.AlterField(
            model_name='zakaz_sapakswotka',
            name='gal_pey_summa_dol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi peýda walýuta'),
        ),
        migrations.AlterField(
            model_name='zakaz_sapakswotka',
            name='jemi_gir_baha',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi girdeji bahasy'),
        ),
        migrations.AlterField(
            model_name='zakaz_sapakswotka',
            name='jemi_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Harydyň jemi kg'),
        ),
        migrations.AlterField(
            model_name='zakaz_swotka',
            name='bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bahasy'),
        ),
        migrations.AlterField(
            model_name='zakaz_swotka',
            name='cyk_summa_dol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi çykdaýjy walýuta'),
        ),
        migrations.AlterField(
            model_name='zakaz_swotka',
            name='gal_pey_summa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi peýda'),
        ),
        migrations.AlterField(
            model_name='zakaz_swotka',
            name='gal_pey_summa_dol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi peýda walýuta'),
        ),
        migrations.AlterField(
            model_name='zakaz_swotka',
            name='jemi_gir_baha',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi girdeji bahasy'),
        ),
    ]
