# Generated by Django 4.2.2 on 2023-07-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0076_alter_aylyk_premya_bellik_alter_aylyk_premya_sebap'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojidanie',
            name='awans',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Awans'),
        ),
        migrations.AddField(
            model_name='ojidanie',
            name='cash_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Nagt pul $'),
        ),
        migrations.AlterField(
            model_name='ojidanie',
            name='cash',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Nagt pul TMT'),
        ),
    ]
