# Generated by Django 4.2.2 on 2023-07-18 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shu', '0077_ojidanie_awans_ojidanie_cash_d_alter_ojidanie_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolek_hasaplar',
            name='user_sent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bolek_hasaplar',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_hasap', to=settings.AUTH_USER_MODEL),
        ),
    ]
