# Generated by Django 4.2.2 on 2023-07-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0078_bolek_hasaplar_user_sent_alter_bolek_hasaplar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojidanie',
            name='tassyk',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
