# Generated by Django 4.2.1 on 2023-07-18 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shu', '0079_alter_ojidanie_tassyk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojidanie',
            name='u_came_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
