# Generated by Django 4.2.1 on 2023-07-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0080_alter_ojidanie_u_came_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolek_hasaplar',
            name='awans',
        ),
        migrations.RemoveField(
            model_name='ojidanie',
            name='awans',
        ),
        migrations.AddField(
            model_name='aylyk_premya',
            name='awans_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Awans $'),
        ),
        migrations.AddField(
            model_name='aylyk_premya',
            name='awans_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Awans TMT'),
        ),
        migrations.AddField(
            model_name='bolek_hasaplar',
            name='awans_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Awans $'),
        ),
        migrations.AddField(
            model_name='bolek_hasaplar',
            name='awans_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Awans TMT'),
        ),
        migrations.AddField(
            model_name='ojidanie',
            name='awans_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Awans $'),
        ),
        migrations.AddField(
            model_name='ojidanie',
            name='awans_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Awans TMT'),
        ),
    ]
