# Generated by Django 4.2.1 on 2023-07-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0081_remove_bolek_hasaplar_awans_remove_ojidanie_awans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aylyk_premya',
            name='jemi_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi $'),
        ),
        migrations.AddField(
            model_name='aylyk_premya',
            name='jemi_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi TMT'),
        ),
    ]
