# Generated by Django 4.2.1 on 2023-07-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0082_aylyk_premya_jemi_d_aylyk_premya_jemi_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='aylyk_premya',
            name='has_sene',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Senesi'),
        ),
        migrations.AlterField(
            model_name='aylyk_premya',
            name='summa_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi $'),
        ),
        migrations.AlterField(
            model_name='aylyk_premya',
            name='summa_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi TMT'),
        ),
    ]
