# Generated by Django 4.2.1 on 2023-07-20 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_cigmal_zawodlar'),
        ('shu', '0085_alter_das_karz_alynanpul_kimden_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export_yukler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kime', models.CharField(blank=True, max_length=100, null=True, verbose_name='Giden edara-kähananyň ady')),
                ('deklorasiya_nomer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şertnama belgisi')),
                ('name_haryt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Markasy')),
                ('summa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Summasy')),
                ('bellik', models.TextField(blank=True, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('kimden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export', to='users.sehler')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.office')),
            ],
            options={
                'verbose_name': 'Exporta gitýän ýük',
                'verbose_name_plural': 'Exporta gitýän ýükler',
            },
        ),
    ]
