# Generated by Django 4.2.1 on 2023-07-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0086_export_yukler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export_yukler',
            name='office',
        ),
        migrations.RemoveField(
            model_name='export_yukler',
            name='summa',
        ),
        migrations.AddField(
            model_name='export_yukler',
            name='summa_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy $'),
        ),
        migrations.AddField(
            model_name='export_yukler',
            name='summa_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy TMT'),
        ),
        migrations.AlterField(
            model_name='export_yukler',
            name='deklorasiya_nomer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diklarasiýa belgisi'),
        ),
        migrations.AlterField(
            model_name='export_yukler',
            name='name_haryt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Näme haryt gitdi'),
        ),
    ]
