# Generated by Django 4.2.1 on 2023-07-21 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_manager_user'),
        ('shu', '0087_remove_export_yukler_office_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='das_isleyan_zawod_tapawut',
            options={'verbose_name': 'Daşary ýurt klient we peýda', 'verbose_name_plural': 'Daşary ýurt klientler we peýda'},
        ),
        migrations.RemoveField(
            model_name='das_isleyan_zawod_tapawut',
            name='haryt_kg',
        ),
        migrations.RemoveField(
            model_name='das_isleyan_zawod_tapawut',
            name='sany',
        ),
        migrations.RemoveField(
            model_name='das_isleyan_zawod_tapawut',
            name='sene',
        ),
        migrations.RemoveField(
            model_name='das_isleyan_zawod_tapawut',
            name='tapawudy_d',
        ),
        migrations.RemoveField(
            model_name='das_isleyan_zawod_tapawut',
            name='tapawudy_m',
        ),
        migrations.AddField(
            model_name='das_isleyan_zawod_tapawut',
            name='bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bahasy $'),
        ),
        migrations.AddField(
            model_name='das_isleyan_zawod_tapawut',
            name='bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bahasy TMT'),
        ),
        migrations.AddField(
            model_name='das_isleyan_zawod_tapawut',
            name='cykdajy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi çykdajy $'),
        ),
        migrations.AddField(
            model_name='das_isleyan_zawod_tapawut',
            name='cykdajy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi çykdajy TMT'),
        ),
        migrations.AddField(
            model_name='das_isleyan_zawod_tapawut',
            name='i_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Işlenen harydyň sany'),
        ),
        migrations.AddField(
            model_name='das_isleyan_zawod_tapawut',
            name='klient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.manager_user'),
        ),
        migrations.AddField(
            model_name='das_isleyan_zawod_tapawut',
            name='peyda_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi galýan peýda $'),
        ),
        migrations.AddField(
            model_name='das_isleyan_zawod_tapawut',
            name='peyda_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi galýan peýda TMT'),
        ),
        migrations.AddField(
            model_name='das_isleyan_zawod_tapawut',
            name='shertnama_nomer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Şertnama belgisi'),
        ),
        migrations.AddField(
            model_name='das_isleyan_zawod_tapawut',
            name='y_sene',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='islenen Senesi'),
        ),
        migrations.AddField(
            model_name='das_isleyan_zawod_tapawut',
            name='z_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Harydyň şertnama sany'),
        ),
        migrations.AddField(
            model_name='das_isleyan_zawod_tapawut',
            name='z_sene',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='zakaz Senesi'),
        ),
        migrations.AlterField(
            model_name='das_isleyan_zawod_tapawut',
            name='jemi_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy $'),
        ),
        migrations.AlterField(
            model_name='das_isleyan_zawod_tapawut',
            name='jemi_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy TMT'),
        ),
    ]
