# Generated by Django 4.2.1 on 2023-07-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0089_remove_das_isleyan_zawod_tapawut_jemi_bahasy_d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='das_isleyan_zawod_tapawut',
            name='y_sene',
            field=models.DateField(blank=True, null=True, verbose_name='islenen Senesi'),
        ),
    ]
