# Generated by Django 4.2.1 on 2023-07-22 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_manager_user'),
        ('shu', '0090_alter_das_isleyan_zawod_tapawut_y_sene'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walyuta_hasap',
            old_name='hasap',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='walyuta_hasap',
            name='karhana',
        ),
        migrations.RemoveField(
            model_name='walyuta_hasap',
            name='sene',
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_summa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi gelen pul')),
                ('c_summa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi giden pul')),
                ('galyndy', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Galyndy')),
                ('sebap', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jemi girdeji-çykdajylaryň sebäbi')),
                ('bellik', models.TextField(blank=True, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('seh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='users.sehler')),
                ('wal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.walyuta_hasap')),
            ],
            options={
                'verbose_name': 'Bakdaky hereket',
                'verbose_name_plural': 'Bakdaky hereketler',
            },
        ),
    ]
