# Generated by Django 4.2.1 on 2023-07-22 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_manager_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shu', '0091_rename_hasap_walyuta_hasap_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import_yukpul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_summa_m', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Geçirilen pul TMT')),
                ('g_summa_d', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Geçirilen pul $')),
                ('a_summa_m', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Alynan pul TMT')),
                ('a_summa_d', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Alynan pul $')),
                ('tapawut_m', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Tapawut puly TMT')),
                ('tapawut_d', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Tapawut puly $')),
                ('bellik', models.TextField(blank=True, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('kimden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_pul', to='users.sehler')),
                ('kime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import: haryt getirýän bilen hasaplaşyk',
                'verbose_name_plural': 'Import: haryt getirýänler bilen hasaplaşyklar',
            },
        ),
        migrations.CreateModel(
            name='Hasaplasylmadyk_algy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa_m', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Algy TMT')),
                ('summa_d', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Algy $')),
                ('sebap', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hasaplaşylmadyk algynyň sebäbi')),
                ('bellik', models.TextField(blank=True, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('kimden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alynmadyk_algy', to='users.sehler')),
            ],
            options={
                'verbose_name': 'Hasaplaşylmadyk algy',
                'verbose_name_plural': 'Hasaplaşylmadyk algyler',
            },
        ),
        migrations.CreateModel(
            name='Hasaplasylan_algy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa_m', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Hasaplaşylan algy TMT')),
                ('summa_d', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Hasaplaşylan algy $')),
                ('nahili_hasaplasylan', models.CharField(blank=True, max_length=500, null=True, verbose_name='Algy nähili hasaplaşylan')),
                ('sebap', models.CharField(blank=True, max_length=500, null=True, verbose_name='Hasaplaşylan algynyň sebäbi')),
                ('bellik', models.TextField(blank=True, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('kimden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alynan_algy', to='users.sehler')),
            ],
            options={
                'verbose_name': 'Hasaplaşylan algy',
                'verbose_name_plural': 'Hasaplaşylan algylar',
            },
        ),
    ]
