# Generated by Django 4.2.1 on 2023-07-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_manager_user'),
        ('shu', '0092_import_yukpul_hasaplasylmadyk_algy_hasaplasylan_algy'),
    ]

    operations = [
        migrations.AddField(
            model_name='aydakydokma_hasabat',
            name='sehs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler'),
        ),
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='sehs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler'),
        ),
        migrations.AddField(
            model_name='aydakysapak_hasabat',
            name='sehs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler'),
        ),
        migrations.AddField(
            model_name='zakaz_dokmaswotka',
            name='sehs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler'),
        ),
        migrations.AddField(
            model_name='zakaz_sapakswotka',
            name='sehs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler'),
        ),
        migrations.AddField(
            model_name='zakaz_swotka',
            name='sehs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler'),
        ),
    ]
