# Generated by Django 4.2.1 on 2023-07-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0094_aydakyhalta_hasabat_zakaz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='zakaz_code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Zakaz belgisi'),
        ),
    ]
