# Generated by Django 4.2.1 on 2023-07-22 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_manager_user'),
        ('shu', '0095_aydakyhalta_hasabat_zakaz_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='aydakydokma_hasabat',
            name='zakaz_code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Zakaz belgisi'),
        ),
        migrations.AddField(
            model_name='aydakydokma_hasabat',
            name='zakaz_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.other_users'),
        ),
        migrations.AddField(
            model_name='aydakysapak_hasabat',
            name='zakaz_code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Zakaz belgisi'),
        ),
        migrations.AddField(
            model_name='aydakysapak_hasabat',
            name='zakaz_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.other_users'),
        ),
    ]
