# Generated by Django 4.2.1 on 2023-07-29 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_primary_seh_alter_sehler_options_sehler_pr_seh'),
        ('shu', '0097_remove_inwentar_bahasy_inwentar_bahasy_d_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Das_isleyan_zawodlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harydyn_ady', models.CharField(blank=True, max_length=500, null=True, verbose_name='Harydyň ady')),
                ('b_haryt_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Zakaz harydyň sany')),
                ('b_haryt_kg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Zakaz haryt kg')),
                ('a_haryt_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Alynan harydyň sany')),
                ('a_haryt_kg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Alynan haryt kg')),
                ('b_bahasy_m', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Berilen bahasy TMT')),
                ('b_bahasy_d', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Berilen Bahasy $')),
                ('b_jemi_bahasy_m', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Berilen jemi bahasy TMT')),
                ('b_jemi_bahasy_d', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Berilen jemi bahasy $')),
                ('a_jemi_bahasy_m', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Alynan jemi bahasy TMT')),
                ('a_jemi_bahasy_d', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Alynan jemi bahasy $')),
                ('tapawut_m', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Tapawudy TMT')),
                ('tapawut_d', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Tapawudy $')),
                ('bellik', models.TextField(blank=True, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
            ],
            options={
                'verbose_name': 'Daşyndan işleşilýän zawoda berilen alynan harydy',
                'verbose_name_plural': 'Daşyndan işleşilýän zawoda berilen alynan harytlary',
            },
        ),
        migrations.CreateModel(
            name='Das_zawod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Zawodyň ady')),
                ('tel', models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefon belgisi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Salgysy')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
            ],
            options={
                'verbose_name': 'Daşyndan işleşilýän zawod',
                'verbose_name_plural': 'Daşyndan işleşilýän zawodlar',
            },
        ),
        migrations.RenameModel(
            old_name='Das_isleyan_zawod_tapawut',
            new_name='Das_yurt_klientler',
        ),
        migrations.DeleteModel(
            name='Alynan_haryt_pul',
        ),
        migrations.DeleteModel(
            name='Berilen_haryt_pul',
        ),
        migrations.AddField(
            model_name='das_isleyan_zawodlar',
            name='zawod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.das_zawod'),
        ),
    ]
