# Generated by Django 4.2.1 on 2023-07-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0098_das_isleyan_zawodlar_das_zawod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='das_isleyan_zawodlar',
            name='g_haryt_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Galan haryt kg'),
        ),
        migrations.AddField(
            model_name='das_isleyan_zawodlar',
            name='g_haryt_sany',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Galan harydyň sany'),
        ),
        migrations.AlterField(
            model_name='das_isleyan_zawodlar',
            name='a_haryt_sany',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Alynan harydyň sany'),
        ),
        migrations.AlterField(
            model_name='das_isleyan_zawodlar',
            name='b_haryt_sany',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Zakaz harydyň sany'),
        ),
    ]
