# Generated by Django 4.2.1 on 2023-07-30 06:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0099_das_isleyan_zawodlar_g_haryt_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='seh',
        ),
        migrations.AlterField(
            model_name='bank',
            name='sebap',
            field=models.TextField(blank=True, null=True, verbose_name='Jemi girdeji-çykdajylaryň sebäbi'),
        ),
        migrations.CreateModel(
            name='Bank_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='F.A.A')),
                ('tel', models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefon belgisi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Salgysy')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('wal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.walyuta_hasap')),
            ],
            options={
                'verbose_name': 'Bank user',
                'verbose_name_plural': 'Bank users',
            },
        ),
        migrations.AddField(
            model_name='bank',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.bank_user'),
        ),
    ]
