# Generated by Django 4.2.1 on 2023-07-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0100_remove_bank_seh_alter_bank_sebap_bank_user_bank_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='shet_nomer',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Walýutaň hasap belgisi'),
        ),
    ]
