# Generated by Django 4.2.1 on 2023-07-30 13:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0102_remove_inwen_spisat_bahasy_inwen_spisat_bahasy_d_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gelen_sklat',
            options={'verbose_name': 'Gelen we giden haryt', 'verbose_name_plural': 'Gelen we giden harytlar'},
        ),
        migrations.RenameField(
            model_name='aydakysklad_hasabat',
            old_name='ahyrky_galyndy',
            new_name='ahyrky_galyndy_kg',
        ),
        migrations.RenameField(
            model_name='aydakysklad_hasabat',
            old_name='yerinde_bar_haryt',
            new_name='yerinde_bar_haryt_kg',
        ),
        migrations.RemoveField(
            model_name='aydakysklad_hasabat',
            name='tapawudy',
        ),
        migrations.AddField(
            model_name='aydakysklad_hasabat',
            name='ahyrky_galyndy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky ahyrky galyndy $'),
        ),
        migrations.AddField(
            model_name='aydakysklad_hasabat',
            name='ahyrky_galyndy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky ahyrky galyndy TMT'),
        ),
        migrations.AddField(
            model_name='aydakysklad_hasabat',
            name='ahyrky_galyndy_sany',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky ahyrky galyndy sany'),
        ),
        migrations.AddField(
            model_name='aydakysklad_hasabat',
            name='gecenay_galyndy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Geçen aýdaky galyndy $'),
        ),
        migrations.AddField(
            model_name='aydakysklad_hasabat',
            name='gecenay_galyndy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Geçen aýdaky galyndy TMT'),
        ),
        migrations.AddField(
            model_name='aydakysklad_hasabat',
            name='haryt_kg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Haryt kg'),
        ),
        migrations.AddField(
            model_name='aydakysklad_hasabat',
            name='oz_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Özüne düşýän bahasy $'),
        ),
        migrations.AddField(
            model_name='aydakysklad_hasabat',
            name='oz_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Özüne düşýän bahasy TMT'),
        ),
        migrations.AddField(
            model_name='aydakysklad_hasabat',
            name='tapawudy_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Aýdaky tapawut kg'),
        ),
        migrations.AddField(
            model_name='aydakysklad_hasabat',
            name='tapawudy_sany',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Aýdaky tapawut sany'),
        ),
        migrations.AddField(
            model_name='aydakysklad_hasabat',
            name='yerinde_bar_haryt_sany',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky ýerinde bar harydyň sany'),
        ),
        migrations.AddField(
            model_name='das_yurt_klientler',
            name='tapawut_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Tapawudy $'),
        ),
        migrations.AddField(
            model_name='das_yurt_klientler',
            name='tapawut_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Tapawudy TMT'),
        ),
        migrations.AddField(
            model_name='gelen_sklat',
            name='g_bellik',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Giden harydyň belligi'),
        ),
        migrations.AddField(
            model_name='gelen_sklat',
            name='g_haryt_kg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Giden haryt kg'),
        ),
        migrations.AddField(
            model_name='gelen_sklat',
            name='g_jemi_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Giden harydyň jemi bahasy $'),
        ),
        migrations.AddField(
            model_name='gelen_sklat',
            name='g_jemi_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Giden harydyň jemi bahasy TMT'),
        ),
        migrations.AddField(
            model_name='gelen_sklat',
            name='g_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Giden harydyň sany'),
        ),
        migrations.AddField(
            model_name='gelen_sklat',
            name='g_sene',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Giden harydyň senesi'),
        ),
        migrations.AddField(
            model_name='gelen_sklat',
            name='haryt_kg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Haryt kg'),
        ),
        migrations.AddField(
            model_name='gelen_sklat',
            name='nira_gitdi',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Haryt nirä gitdi'),
        ),
        migrations.AddField(
            model_name='giden_sklat',
            name='gel_sklad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.gelen_sklat'),
        ),
        migrations.AddField(
            model_name='giden_sklat',
            name='haryt_kg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Haryt kg'),
        ),
        migrations.AlterField(
            model_name='aydakysklad_hasabat',
            name='gecenay_galyndy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Geçen aýdaky galyndy kg'),
        ),
    ]
