# Generated by Django 4.2.1 on 2023-07-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0103_alter_gelen_sklat_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Giden_sklat',
        ),
    ]
