# Generated by Django 4.2.1 on 2023-07-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0106_rename_gecenay_galyndy_aydakysklad_hasabat_gecenay_galyndy_kg_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aydakysapak_hasabat',
            options={'verbose_name': 'Sapak seh aýlyk hasabaty', 'verbose_name_plural': 'Sapak seh aýlyk hasabatlary'},
        ),
        migrations.AlterModelOptions(
            name='sapak_seh_ay_tabel',
            options={'verbose_name': 'Aýdaky dokalan sapak hasabaty (Tabeller)', 'verbose_name_plural': 'Aýdaky dokalan sapak hasabatlary (Tabeller)'},
        ),
        migrations.AddField(
            model_name='das_isleyan_zawodlar',
            name='has_sene',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Senesi'),
        ),
        migrations.AddField(
            model_name='das_isleyan_zawodlar',
            name='satylan_haryt_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Satylan haryt kg'),
        ),
        migrations.AddField(
            model_name='das_isleyan_zawodlar',
            name='satylan_haryt_sany',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Satylan harydyň sany'),
        ),
    ]
