# Generated by Django 4.2.1 on 2023-07-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0107_alter_aydakysapak_hasabat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='das_isleyan_zawodlar',
            name='t_haryt_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Taýýar haryt kg'),
        ),
        migrations.AddField(
            model_name='das_isleyan_zawodlar',
            name='t_haryt_sany',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Taýýar harydyň sany'),
        ),
    ]
