# Generated by Django 4.2.1 on 2023-08-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0109_inwen_spisat_j_bahasy_d_inwen_spisat_j_bahasy_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aydakydokma_hasabat',
            name='cykrulon_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Çykan rulonyň bahasy'),
        ),
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='abathalta_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Abat haltaň bahasy'),
        ),
        migrations.AddField(
            model_name='aydakysapak_hasabat',
            name='cyksapak_bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Çykan sapagyň bahasy'),
        ),
    ]
