# Generated by Django 4.2.1 on 2023-08-02 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_primary_seh_alter_sehler_options_sehler_pr_seh'),
        ('shu', '0111_remove_aydaky_dokma_jemi_bahasy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz_balans',
            name='seh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler'),
        ),
    ]
