# Generated by Django 4.2.1 on 2023-08-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0113_remove_customer_accountsapak_d_gornusi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasaplasylmadyk_algy',
            name='kimden',
        ),
        migrations.RemoveField(
            model_name='zakaz_swotka',
            name='bahasy',
        ),
        migrations.RemoveField(
            model_name='zakaz_swotka',
            name='jemi_gir_baha',
        ),
        migrations.RemoveField(
            model_name='zakaz_swotka',
            name='jemi_sany',
        ),
        migrations.AddField(
            model_name='aydaky_halta',
            name='abathalta_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Abat haltaň kg'),
        ),
        migrations.AddField(
            model_name='aydaky_halta',
            name='abathalta_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Abat haltaň sany'),
        ),
        migrations.AddField(
            model_name='aydaky_halta',
            name='brakhalta_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Brak haltan kg'),
        ),
        migrations.AddField(
            model_name='aydaky_halta',
            name='brakhalta_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Brak haltaň sany'),
        ),
        migrations.AddField(
            model_name='aydaky_halta',
            name='ganarhalta_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Ganar haltan kg'),
        ),
        migrations.AddField(
            model_name='aydaky_halta',
            name='ganarhalta_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Ganar haltaň sany'),
        ),
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='abathalta_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Abat haltaň kg'),
        ),
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='abathalta_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Abat haltaň sany'),
        ),
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='brakhalta_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Brak haltaň bahasy $'),
        ),
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='brakhalta_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Brak haltaň bahasy TMT'),
        ),
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='brakhalta_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Brak haltan kg'),
        ),
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='brakhalta_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Brak haltaň sany'),
        ),
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='ganarhalta_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Ganar haltaň bahasy $'),
        ),
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='ganarhalta_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Ganar haltaň bahasy TMT'),
        ),
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='ganarhalta_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Ganar haltan kg'),
        ),
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='ganarhalta_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Ganar haltaň sany'),
        ),
        migrations.AddField(
            model_name='zakaz_swotka',
            name='abathalta_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Abat haltaň sany'),
        ),
        migrations.AddField(
            model_name='zakaz_swotka',
            name='brakhalta_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Brak haltaň sany'),
        ),
        migrations.AddField(
            model_name='zakaz_swotka',
            name='ganarhalta_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Ganar haltaň sany'),
        ),
        migrations.AlterField(
            model_name='sklad_swotkalar',
            name='j_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi alynan bahasy manatda'),
        ),
        migrations.DeleteModel(
            name='Hasaplasylan_algy',
        ),
        migrations.DeleteModel(
            name='Hasaplasylmadyk_algy',
        ),
    ]
