# Generated by Django 4.2.1 on 2023-08-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0116_aydaky_halta_has_sene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aydakyhalta_hasabat',
            name='ahyrky_galyndy',
        ),
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='ahyrky_galyndy_abat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jemi aýdaky abat haltanyň ahyrky galyndy sany'),
        ),
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='ahyrky_galyndy_brak',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jemi aýdaky brak haltanyň ahyrky galyndy sany'),
        ),
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='ahyrky_galyndy_ganar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jemi aýdaky ganar haltanyň ahyrky galyndy sany'),
        ),
        migrations.AlterField(
            model_name='zakaz_swotka',
            name='cyk_summa_dol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Jemi çykdaýjy walýuta'),
        ),
        migrations.AlterField(
            model_name='zakaz_swotka',
            name='gal_pey_summa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Jemi peýda'),
        ),
        migrations.AlterField(
            model_name='zakaz_swotka',
            name='gal_pey_summa_dol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Jemi peýda walýuta'),
        ),
    ]
