# Generated by Django 4.2.1 on 2023-08-07 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0117_remove_aydakyhalta_hasabat_ahyrky_galyndy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz_swotka',
            name='h_gornusi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.halta_gornus'),
        ),
        migrations.AddField(
            model_name='zakaz_swotka',
            name='h_olceg',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Haltaň ölçegi'),
        ),
    ]
