# Generated by Django 4.2.1 on 2023-08-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0118_zakaz_swotka_h_gornusi_zakaz_swotka_h_olceg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zakaz_swotka',
            old_name='sene_id',
            new_name='has_sene',
        ),
    ]
