# Generated by Django 4.2.1 on 2023-08-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0120_remove_aydakyhalta_hasabat_gecenay_galyndy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aydakyhalta_hasabat',
            name='gecenay_galyndy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Geçen aýdaky galyndy'),
        ),
    ]
