# Generated by Django 4.2.1 on 2023-08-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0121_aydakyhalta_hasabat_gecenay_galyndy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aydakyhalta_hasabat',
            name='gecenay_galyndy_abat',
        ),
        migrations.RemoveField(
            model_name='aydakyhalta_hasabat',
            name='gecenay_galyndy_brak',
        ),
        migrations.RemoveField(
            model_name='aydakyhalta_hasabat',
            name='gecenay_galyndy_ganar',
        ),
        migrations.RemoveField(
            model_name='aydakyhalta_hasabat',
            name='jemi_sany',
        ),
        migrations.AddField(
            model_name='zakaz_swotka',
            name='jemi_baha_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi girdeji bahasy $'),
        ),
        migrations.AddField(
            model_name='zakaz_swotka',
            name='jemi_baha_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi girdeji bahasy TMT'),
        ),
    ]
