# Generated by Django 4.2.1 on 2023-08-08 05:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_primary_seh_alter_sehler_options_sehler_pr_seh'),
        ('shu', '0122_remove_aydakyhalta_hasabat_gecenay_galyndy_abat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haltaseh_sklad_satylan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_olceg', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Haltaň ölçegi')),
                ('abathalta_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Abat haltaň sany')),
                ('brakhalta_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Brak haltaň sany')),
                ('ganarhalta_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Ganar haltaň sany')),
                ('gecenay_galyndy', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Geçen aýdaky galyndy')),
                ('satylan_halta_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Jemi aýdaky satylan haltaň sany')),
                ('wozwrat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky wozwrat')),
                ('ahyrky_galyndy_abat', models.IntegerField(blank=True, null=True, verbose_name='Jemi aýdaky abat haltanyň ahyrky galyndy sany')),
                ('ahyrky_galyndy_brak', models.IntegerField(blank=True, null=True, verbose_name='Jemi aýdaky brak haltanyň ahyrky galyndy sany')),
                ('ahyrky_galyndy_ganar', models.IntegerField(blank=True, null=True, verbose_name='Jemi aýdaky ganar haltanyň ahyrky galyndy sany')),
                ('yerinde_bar_haryt', models.IntegerField(blank=True, default=None, null=True, verbose_name='Jemi aýdaky ýerinde bar harydyň sany')),
                ('tapawudy', models.IntegerField(blank=True, default=None, null=True, verbose_name='Aýdaky tapawut')),
                ('bellik', models.TextField(blank=True, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('has_sene', models.IntegerField(blank=True, default=None, null=True, verbose_name='Senesi')),
                ('h_gornusi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.halta_gornus')),
                ('sehs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler')),
            ],
            options={
                'verbose_name': 'Halta seh skladan satylan önüm',
                'verbose_name_plural': 'Halta seh skladan satylan önümler',
            },
        ),
        migrations.CreateModel(
            name='Haltaseh_sklad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_olceg', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Haltaň ölçegi')),
                ('abathalta_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Abat haltaň sany')),
                ('brakhalta_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Brak haltaň sany')),
                ('ganarhalta_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Ganar haltaň sany')),
                ('gecenay_galyndy', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Geçen aýdaky galyndy')),
                ('satylan_halta_sany', models.IntegerField(blank=True, default=None, null=True, verbose_name='Jemi aýdaky satylan haltaň sany')),
                ('wozwrat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky wozwrat')),
                ('ahyrky_galyndy_abat', models.IntegerField(blank=True, null=True, verbose_name='Jemi aýdaky abat haltanyň ahyrky galyndy sany')),
                ('ahyrky_galyndy_brak', models.IntegerField(blank=True, null=True, verbose_name='Jemi aýdaky brak haltanyň ahyrky galyndy sany')),
                ('ahyrky_galyndy_ganar', models.IntegerField(blank=True, null=True, verbose_name='Jemi aýdaky ganar haltanyň ahyrky galyndy sany')),
                ('yerinde_bar_haryt', models.IntegerField(blank=True, default=None, null=True, verbose_name='Jemi aýdaky ýerinde bar harydyň sany')),
                ('tapawudy', models.IntegerField(blank=True, default=None, null=True, verbose_name='Aýdaky tapawut')),
                ('bellik', models.TextField(blank=True, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('has_sene', models.IntegerField(blank=True, default=None, null=True, verbose_name='Senesi')),
                ('h_gornusi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.halta_gornus')),
                ('sehs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sehler')),
            ],
            options={
                'verbose_name': 'Halta seh sklada giden önüm',
                'verbose_name_plural': 'Halta seh sklada giden önümler',
            },
        ),
    ]
