# Generated by Django 4.2.1 on 2023-08-08 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0123_haltaseh_sklad_satylan_haltaseh_sklad'),
    ]

    operations = [
        migrations.AddField(
            model_name='haltaseh_sklad_satylan',
            name='gel_sklad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.haltaseh_sklad'),
        ),
    ]
