# Generated by Django 4.2.1 on 2023-08-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0125_rename_ahyrky_galyndy_abat_haltaseh_sklad_satylan_ahyrky_galyndy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haltaseh_sklad',
            old_name='ahyrky_galyndy_abat',
            new_name='ahyrky_galyndy',
        ),
        migrations.RemoveField(
            model_name='haltaseh_sklad',
            name='ahyrky_galyndy_brak',
        ),
        migrations.RemoveField(
            model_name='haltaseh_sklad',
            name='ahyrky_galyndy_ganar',
        ),
        migrations.RemoveField(
            model_name='haltaseh_sklad',
            name='tapawudy',
        ),
        migrations.RemoveField(
            model_name='haltaseh_sklad',
            name='yerinde_bar_haryt',
        ),
    ]
