# Generated by Django 4.2.1 on 2023-08-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0128_haltaseh_sklad_satylan_zakaz_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='haltaseh_sklad_satylan',
            name='abathalta_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Abat haltaň sany'),
        ),
        migrations.AddField(
            model_name='haltaseh_sklad_satylan',
            name='brakhalta_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Brak haltaň sany'),
        ),
        migrations.AddField(
            model_name='haltaseh_sklad_satylan',
            name='ganarhalta_sany',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Ganar haltaň sany'),
        ),
    ]
