# Generated by Django 4.2.1 on 2023-08-09 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_primary_seh_alter_sehler_options_sehler_pr_seh'),
        ('shu', '0129_haltaseh_sklad_satylan_abathalta_sany_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zakaz_dokmaswotka',
            options={'verbose_name': 'Dokma seh peýda swotka', 'verbose_name_plural': 'Dokma seh peýda swotkalar'},
        ),
        migrations.AlterModelOptions(
            name='zakaz_sapakswotka',
            options={'verbose_name': 'Sapak seh peýda swotka', 'verbose_name_plural': 'Sapak seh peýda swotkalar'},
        ),
        migrations.AlterModelOptions(
            name='zakaz_swotka',
            options={'verbose_name': 'Halta seh peýda swotka', 'verbose_name_plural': 'Halta seh peýda swotkalar'},
        ),
        migrations.RenameField(
            model_name='dokmaseh_sklad',
            old_name='h_gornusi',
            new_name='d_gornusi',
        ),
        migrations.RenameField(
            model_name='dokmaseh_sklad_satylan',
            old_name='h_gornusi',
            new_name='d_gornusi',
        ),
        migrations.RenameField(
            model_name='sapakseh_sklad',
            old_name='h_gornusi',
            new_name='d_gornusi',
        ),
        migrations.RenameField(
            model_name='sapakseh_sklad_satylan',
            old_name='h_gornusi',
            new_name='d_gornusi',
        ),
        migrations.RenameField(
            model_name='zakaz_dokmaswotka',
            old_name='sene_id',
            new_name='has_sene',
        ),
        migrations.RenameField(
            model_name='zakaz_sapakswotka',
            old_name='sene_id',
            new_name='has_sene',
        ),
        migrations.RemoveField(
            model_name='dokmaseh_sklad',
            name='h_olceg',
        ),
        migrations.RemoveField(
            model_name='dokmaseh_sklad_satylan',
            name='h_olceg',
        ),
        migrations.RemoveField(
            model_name='gundelik_dokma',
            name='zakaz_user',
        ),
        migrations.RemoveField(
            model_name='gundelik_halta',
            name='zakaz_user',
        ),
        migrations.RemoveField(
            model_name='gundelik_sapak',
            name='zakaz_user',
        ),
        migrations.RemoveField(
            model_name='sapakseh_sklad',
            name='h_olceg',
        ),
        migrations.RemoveField(
            model_name='sapakseh_sklad_satylan',
            name='h_olceg',
        ),
        migrations.RemoveField(
            model_name='zakaz_dokmaswotka',
            name='bahasy',
        ),
        migrations.RemoveField(
            model_name='zakaz_dokmaswotka',
            name='jemi_gir_baha',
        ),
        migrations.RemoveField(
            model_name='zakaz_sapakswotka',
            name='bahasy',
        ),
        migrations.RemoveField(
            model_name='zakaz_sapakswotka',
            name='jemi_gir_baha',
        ),
        migrations.AddField(
            model_name='dokmaseh_sklad_satylan',
            name='jemi_dok_rulon',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky dokalan rulonyň kg'),
        ),
        migrations.AddField(
            model_name='dokmaseh_sklad_satylan',
            name='zakaz_code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Zakaz belgisi'),
        ),
        migrations.AddField(
            model_name='dokmaseh_sklad_satylan',
            name='zakaz_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.other_users'),
        ),
        migrations.AddField(
            model_name='sapakseh_sklad_satylan',
            name='jemi_dok_sapak',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky sapagyň kg'),
        ),
        migrations.AddField(
            model_name='sapakseh_sklad_satylan',
            name='zakaz_code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Zakaz belgisi'),
        ),
        migrations.AddField(
            model_name='sapakseh_sklad_satylan',
            name='zakaz_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.other_users'),
        ),
        migrations.AddField(
            model_name='zakaz_dokmaswotka',
            name='d_gornusi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.halta_gornus'),
        ),
        migrations.AddField(
            model_name='zakaz_dokmaswotka',
            name='jemi_baha_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi girdeji bahasy $'),
        ),
        migrations.AddField(
            model_name='zakaz_dokmaswotka',
            name='jemi_baha_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi girdeji bahasy TMT'),
        ),
        migrations.AddField(
            model_name='zakaz_sapakswotka',
            name='d_gornusi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.halta_gornus'),
        ),
        migrations.AddField(
            model_name='zakaz_sapakswotka',
            name='jemi_baha_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi girdeji bahasy $'),
        ),
        migrations.AddField(
            model_name='zakaz_sapakswotka',
            name='jemi_baha_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi girdeji bahasy TMT'),
        ),
        migrations.AlterField(
            model_name='dokmaseh_sklad_satylan',
            name='gel_sklad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.dokmaseh_sklad'),
        ),
    ]
