# Generated by Django 4.2.1 on 2023-08-09 09:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0130_alter_zakaz_dokmaswotka_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='das_isleyan_zawodlar',
            options={'verbose_name': 'Daşyndan işleşilýän zawoda berilen harydy', 'verbose_name_plural': 'Daşyndan işleşilýän zawoda berilen harytlary'},
        ),
        migrations.RemoveField(
            model_name='das_isleyan_zawodlar',
            name='a_haryt_kg',
        ),
        migrations.RemoveField(
            model_name='das_isleyan_zawodlar',
            name='a_haryt_sany',
        ),
        migrations.RemoveField(
            model_name='das_isleyan_zawodlar',
            name='a_jemi_bahasy_d',
        ),
        migrations.RemoveField(
            model_name='das_isleyan_zawodlar',
            name='a_jemi_bahasy_m',
        ),
        migrations.RemoveField(
            model_name='das_isleyan_zawodlar',
            name='t_haryt_kg',
        ),
        migrations.RemoveField(
            model_name='das_isleyan_zawodlar',
            name='t_haryt_sany',
        ),
        migrations.AlterField(
            model_name='zakaz_dokmaswotka',
            name='cyk_summa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Jemi çykdaýjy'),
        ),
        migrations.AlterField(
            model_name='zakaz_dokmaswotka',
            name='cyk_summa_dol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Jemi çykdaýjy walýuta'),
        ),
        migrations.AlterField(
            model_name='zakaz_dokmaswotka',
            name='gal_pey_summa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Jemi peýda'),
        ),
        migrations.AlterField(
            model_name='zakaz_dokmaswotka',
            name='gal_pey_summa_dol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Jemi peýda walýuta'),
        ),
        migrations.AlterField(
            model_name='zakaz_sapakswotka',
            name='cyk_summa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Jemi çykdaýjy'),
        ),
        migrations.AlterField(
            model_name='zakaz_sapakswotka',
            name='cyk_summa_dol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Jemi çykdaýjy walýuta'),
        ),
        migrations.AlterField(
            model_name='zakaz_sapakswotka',
            name='gal_pey_summa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Jemi peýda'),
        ),
        migrations.AlterField(
            model_name='zakaz_sapakswotka',
            name='gal_pey_summa_dol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Jemi peýda walýuta'),
        ),
        migrations.CreateModel(
            name='Das_is_zawod_Alynan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harydyn_ady', models.CharField(blank=True, max_length=500, null=True, verbose_name='Harydyň ady')),
                ('a_haryt_sany', models.IntegerField(blank=True, default=0, null=True, verbose_name='Alynan harydyň sany')),
                ('a_haryt_kg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Alynan haryt kg')),
                ('a_jemi_bahasy_m', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Alynan jemi bahasy TMT')),
                ('a_jemi_bahasy_d', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Alynan jemi bahasy $')),
                ('bellik', models.TextField(blank=True, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('has_sene', models.IntegerField(blank=True, default=None, null=True, verbose_name='Senesi')),
                ('zak_berilen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.das_isleyan_zawodlar')),
                ('zawod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.das_zawod')),
            ],
            options={
                'verbose_name': 'Daşyndan işleşilýän zawoda alynan harydy',
                'verbose_name_plural': 'Daşyndan işleşilýän zawoda alynan harytlary',
            },
        ),
    ]
