# Generated by Django 4.2.1 on 2023-08-09 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0131_alter_das_isleyan_zawodlar_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='das_karz_alynanpul',
            name='b_summa_d',
        ),
        migrations.RemoveField(
            model_name='das_karz_alynanpul',
            name='b_summa_m',
        ),
        migrations.RemoveField(
            model_name='das_karz_alynanpul',
            name='kimden',
        ),
        migrations.RemoveField(
            model_name='das_karz_alynanpul',
            name='kime',
        ),
        migrations.AddField(
            model_name='das_karz_alynanpul',
            name='karzcy',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Kime bermeli we kimden almaly karz puly'),
        ),
        migrations.CreateModel(
            name='Karz_yzyna_berilen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karzcy', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Kime bermeli we kimden almaly karz puly')),
                ('b_summa_m', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi berilen TMT')),
                ('b_summa_d', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi berilen $')),
                ('jemi_m', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi TMT')),
                ('jemi_d', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi $')),
                ('sebap', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jemi girdejileriniň sebäbi')),
                ('bellik', models.TextField(blank=True, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Senesi')),
                ('has_sene', models.IntegerField(blank=True, default=None, null=True, verbose_name='Senesi')),
                ('alynan_karz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.das_karz_alynanpul')),
            ],
            options={
                'verbose_name': 'Daşyndan berilen karz pul',
                'verbose_name_plural': 'Daşyndan berilen karz pullar',
            },
        ),
    ]
