# Generated by Django 4.2.1 on 2023-08-09 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_primary_seh_alter_sehler_options_sehler_pr_seh'),
        ('shu', '0132_remove_das_karz_alynanpul_b_summa_d_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='das_yurt_klientler',
            old_name='z_sene',
            new_name='sene',
        ),
        migrations.RemoveField(
            model_name='das_yurt_klientler',
            name='cykdajy_d',
        ),
        migrations.RemoveField(
            model_name='das_yurt_klientler',
            name='cykdajy_m',
        ),
        migrations.RemoveField(
            model_name='das_yurt_klientler',
            name='i_sany',
        ),
        migrations.RemoveField(
            model_name='das_yurt_klientler',
            name='j_bahasy_d',
        ),
        migrations.RemoveField(
            model_name='das_yurt_klientler',
            name='j_bahasy_m',
        ),
        migrations.RemoveField(
            model_name='das_yurt_klientler',
            name='y_sene',
        ),
        migrations.RemoveField(
            model_name='karz_yzyna_berilen',
            name='jemi_d',
        ),
        migrations.RemoveField(
            model_name='karz_yzyna_berilen',
            name='jemi_m',
        ),
        migrations.CreateModel(
            name='Das_yurt_klient_cykdajy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shertnama_nomer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şertnama belgisi')),
                ('harydyn_ady', models.CharField(blank=True, max_length=500, null=True, verbose_name='Harydyň ady')),
                ('i_sany', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Işlenen harydyň möçberi')),
                ('j_bahasy_m', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy TMT')),
                ('j_bahasy_d', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy $')),
                ('cykdajy_m', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi çykdajy TMT')),
                ('cykdajy_d', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi çykdajy $')),
                ('bellik', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Bellik')),
                ('sene', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='zakaz Senesi')),
                ('has_sene', models.IntegerField(blank=True, default=None, null=True, verbose_name='Senesi')),
                ('gir_klient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.das_yurt_klientler')),
                ('klient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.manager_user')),
            ],
            options={
                'verbose_name': 'Daşary ýurt klient çykdajysy',
                'verbose_name_plural': 'Daşary ýurt klientler çykdajylary',
            },
        ),
    ]
