# Generated by Django 4.2.2 on 2023-08-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0134_dokmaseh_sklad_cykrulon_bahasy_d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolek_hasaplar',
            name='oj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shu.ojidanie'),
        ),
        migrations.AlterField(
            model_name='aydaky_dokma',
            name='jemi_cyk_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Jemi ayda çykan rulonyň kg'),
        ),
        migrations.AlterField(
            model_name='aydaky_halta',
            name='abathalta_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Abat haltaň kg'),
        ),
        migrations.AlterField(
            model_name='aydaky_halta',
            name='brakhalta_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Brak haltan kg'),
        ),
        migrations.AlterField(
            model_name='aydaky_halta',
            name='ganarhalta_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Ganar haltan kg'),
        ),
        migrations.AlterField(
            model_name='aydaky_halta',
            name='jemi_abat_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Jemi ayda abat haltaň kg'),
        ),
        migrations.AlterField(
            model_name='aydaky_halta',
            name='jemi_brak_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Jemi ayda brak haltaň kg'),
        ),
        migrations.AlterField(
            model_name='aydaky_halta',
            name='jemi_ganar_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Jemi ayda ganar haltaň kg'),
        ),
        migrations.AlterField(
            model_name='aydaky_sapak',
            name='jemi_cyk_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Jemi aydaky sapagyň kg'),
        ),
        migrations.AlterField(
            model_name='aydakydokma_hasabat',
            name='jemi_dok_rulon',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky dokalan rulonyň kg'),
        ),
        migrations.AlterField(
            model_name='aydakydokma_hasabat',
            name='satylan_dokma_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky satylan dokmanyň kg'),
        ),
        migrations.AlterField(
            model_name='aydakydokma_hasabat',
            name='tapawudy',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Aýdaky tapawut'),
        ),
        migrations.AlterField(
            model_name='aydakydokma_hasabat',
            name='yerinde_bar_haryt',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky ýerinde bar harydyň kg'),
        ),
        migrations.AlterField(
            model_name='aydakyhalta_hasabat',
            name='abathalta_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Abat haltaň kg'),
        ),
        migrations.AlterField(
            model_name='aydakyhalta_hasabat',
            name='brakhalta_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Brak haltan kg'),
        ),
        migrations.AlterField(
            model_name='aydakyhalta_hasabat',
            name='ganarhalta_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Ganar haltan kg'),
        ),
        migrations.AlterField(
            model_name='aydakyhalta_hasabat',
            name='wozwrat',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky wozwrat'),
        ),
        migrations.AlterField(
            model_name='aydakysapak_hasabat',
            name='jemi_dok_sapak',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky sapagyň kg'),
        ),
        migrations.AlterField(
            model_name='dokmaseh_sklad',
            name='ahyrky_galyndy',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Jemi aýdaky abat haltanyň ahyrky galyndy kg'),
        ),
        migrations.AlterField(
            model_name='dokmaseh_sklad',
            name='gecenay_galyndy',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Geçen aýdaky galyndy'),
        ),
        migrations.AlterField(
            model_name='dokmaseh_sklad',
            name='jemi_dok_rulon',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky dokalan rulonyň kg'),
        ),
        migrations.AlterField(
            model_name='dokmaseh_sklad',
            name='wozwrat',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky wozwrat'),
        ),
        migrations.AlterField(
            model_name='dokmaseh_sklad_satylan',
            name='jemi_dok_rulon',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky dokalan rulonyň kg'),
        ),
        migrations.AlterField(
            model_name='dokmaseh_sklad_satylan',
            name='satylan_dokma_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky satylan dokmanyň kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_dokma',
            name='cykrulon_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Çykan rulonyň kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_dokma',
            name='wozwrat_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Wozwrat kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='abathalta_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Abat haltaň kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='brakhalta_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Brak haltan kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='ganarhalta_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Ganar haltan kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='katyska_agram',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Katuşkaň agramy kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_halta',
            name='sarp_sapak_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Dikilyan halta gityan sapak kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_sapak',
            name='katyska_agram',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Katuşkaň agramy kg'),
        ),
        migrations.AlterField(
            model_name='gundelik_sapak',
            name='wozwrat_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Wozwrat kg'),
        ),
        migrations.AlterField(
            model_name='sapakseh_sklad',
            name='ahyrky_galyndy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Jemi aýdaky abat haltanyň ahyrky galyndy sany'),
        ),
        migrations.AlterField(
            model_name='sapakseh_sklad',
            name='jemi_dok_sapak',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky sapagyň kg'),
        ),
        migrations.AlterField(
            model_name='sapakseh_sklad',
            name='satylan_sapak_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky satylan sapagyň kg'),
        ),
        migrations.AlterField(
            model_name='sapakseh_sklad_satylan',
            name='satylan_sapak_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Jemi aýdaky satylan sapagyň kg'),
        ),
        migrations.AlterField(
            model_name='world_cygmal',
            name='bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bahasy $'),
        ),
        migrations.AlterField(
            model_name='world_cygmal',
            name='bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bahasy TMT'),
        ),
        migrations.AlterField(
            model_name='world_cygmal',
            name='j_bahasy_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy $'),
        ),
        migrations.AlterField(
            model_name='world_cygmal',
            name='j_bahasy_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Jemi bahasy TMT'),
        ),
        migrations.AlterField(
            model_name='zakaz_dokmaswotka',
            name='jemi_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Harydyň kg'),
        ),
        migrations.AlterField(
            model_name='zakaz_sapakswotka',
            name='jemi_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Harydyň jemi kg'),
        ),
    ]
