# Generated by Django 4.2.2 on 2023-08-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shu', '0135_bolek_hasaplar_oj_alter_aydaky_dokma_jemi_cyk_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gundelik_sapak',
            name='cyksapak_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Çykan sapak kg'),
        ),
    ]
